using static Content.Client.AU14.ColonyEconomy.ColonyEconomyLoc;
using Content.Shared.AU14.ColonyEconomy;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.AU14.ColonyEconomy;

[GenerateTypedNameReferences]
public sealed partial class AdminConsoleWindow : DefaultWindow
{
    public AdminConsoleWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateState(AdminConsoleBuiState state)
    {
        ColonyBudgetLabel.Text = Target("cmu-colony-economy-colony-budget", $"Colony Budget: ${state.ColonyBudget:F0}", ("budget", state.ColonyBudget.ToString("F0")));
        CurrentTaxLabel.Text = Target("cmu-colony-economy-current-sales-tax", $"Current Sales Tax: {state.SalesTaxPercent:F0}%", ("percent", state.SalesTaxPercent.ToString("F0")));
        TaxInput.Text = $"{state.SalesTaxPercent:F0}";
        CurrentIncomeTaxLabel.Text = Target("cmu-colony-economy-current-income-tax", $"Current Income Tax: {state.IncomeTaxPercent:F0}%", ("percent", state.IncomeTaxPercent.ToString("F0")));
        IncomeTaxInput.Text = $"{state.IncomeTaxPercent:F0}";
        UpdateEconomyStatus(state.EconomyStatus);
    }

    private void UpdateEconomyStatus(EconomyStatusState econ)
    {
        EconomyStatusPanel.RemoveAllChildren();
        EconomyStatusPanel.AddChild(new Label { Text = Target("cmu-ambassador-ui-sales-tax", $"Sales Tax: {econ.SalesTaxPercent:F0}%", ("percent", econ.SalesTaxPercent.ToString("F0"))) });
        EconomyStatusPanel.AddChild(new Label { Text = Target("cmu-ambassador-ui-income-tax", $"Income Tax: {econ.IncomeTaxPercent:F0}%", ("percent", econ.IncomeTaxPercent.ToString("F0"))) });
        EconomyStatusPanel.AddChild(new Label { Text = Target("cmu-ambassador-ui-transit-tariff", $"Transit Tariff: {econ.TransitTariffPercent:F0}%", ("percent", econ.TransitTariffPercent.ToString("F0"))) });

        if (econ.ActiveEmbargoes.Count > 0)
            EconomyStatusPanel.AddChild(new Label { Text = Target("cmu-ambassador-ui-active-embargoes", $"Active Embargoes: {string.Join(", ", econ.ActiveEmbargoes)}", ("factions", string.Join(", ", econ.ActiveEmbargoes))), StyleClasses = { "Caution" } });
        else
            EconomyStatusPanel.AddChild(new Label { Text = Target("cmu-ambassador-ui-no-embargoes", "Embargoes: None"), StyleClasses = { "LabelSubText" } });

        if (econ.ActiveTradePacts.Count > 0)
            EconomyStatusPanel.AddChild(new Label { Text = Target("cmu-ambassador-ui-active-trade-pacts", $"Active Trade Pacts: {string.Join(", ", econ.ActiveTradePacts)}", ("factions", string.Join(", ", econ.ActiveTradePacts))) });
        else
            EconomyStatusPanel.AddChild(new Label { Text = Target("cmu-ambassador-ui-no-trade-pacts", "Trade Pacts: None"), StyleClasses = { "LabelSubText" } });
    }
}
