using static Content.Client.AU14.ColonyEconomy.ColonyEconomyLoc;
using Content.Shared.AU14.ColonyEconomy;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.AU14.ColonyEconomy;

[GenerateTypedNameReferences]
public sealed partial class CorporateConsoleWindow : DefaultWindow
{
    public CorporateConsoleWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateState(CorporateConsoleBuiState state)
    {
        CorporateBudgetLabel.Text = Target("cmu-colony-economy-corporate-budget", $"Corporate Budget: ${state.CorporateBudget:F0}", ("budget", state.CorporateBudget.ToString("F0")));
        CurrentTariffLabel.Text = Target("cmu-colony-economy-current-transit-tariff", $"Current Transit Tariff: {state.TransitTariffPercent:F0}%", ("percent", state.TransitTariffPercent.ToString("F0")));
        TariffInput.Text = $"{state.TransitTariffPercent:F0}";

        var incomeTax = state.EconomyStatus.IncomeTaxPercent;
        WithdrawTaxNote.Text = incomeTax > 0
            ? Target("cmu-colony-economy-withdraw-income-tax-note", $"Note: Withdrawals are subject to {incomeTax:F0}% income tax.", ("percent", incomeTax.ToString("F0")))
            : Target("cmu-colony-economy-withdraw-no-income-tax", "No income tax on withdrawals.");

        UpdateEconomyStatus(state.EconomyStatus);
    }

    private void UpdateEconomyStatus(EconomyStatusState econ)
    {
        EconomyStatusPanel.RemoveAllChildren();
        EconomyStatusPanel.AddChild(new Label { Text = Target("cmu-ambassador-ui-sales-tax", $"Sales Tax: {econ.SalesTaxPercent:F0}%", ("percent", econ.SalesTaxPercent.ToString("F0"))) });
        EconomyStatusPanel.AddChild(new Label { Text = Target("cmu-ambassador-ui-income-tax", $"Income Tax: {econ.IncomeTaxPercent:F0}%", ("percent", econ.IncomeTaxPercent.ToString("F0"))) });
        EconomyStatusPanel.AddChild(new Label { Text = Target("cmu-ambassador-ui-transit-tariff", $"Transit Tariff: {econ.TransitTariffPercent:F0}%", ("percent", econ.TransitTariffPercent.ToString("F0"))) });

        if (econ.ActiveEmbargoes.Count > 0)
            EconomyStatusPanel.AddChild(new Label { Text = Target("cmu-ambassador-ui-active-embargoes", $"Active Embargoes: {string.Join(", ", econ.ActiveEmbargoes)}", ("factions", string.Join(", ", econ.ActiveEmbargoes))), StyleClasses = { "Caution" } });
        else
            EconomyStatusPanel.AddChild(new Label { Text = Target("cmu-ambassador-ui-no-embargoes", "Embargoes: None"), StyleClasses = { "LabelSubText" } });

        if (econ.ActiveTradePacts.Count > 0)
            EconomyStatusPanel.AddChild(new Label { Text = Target("cmu-ambassador-ui-active-trade-pacts", $"Active Trade Pacts: {string.Join(", ", econ.ActiveTradePacts)}", ("factions", string.Join(", ", econ.ActiveTradePacts))) });
        else
            EconomyStatusPanel.AddChild(new Label { Text = Target("cmu-ambassador-ui-no-trade-pacts", "Trade Pacts: None"), StyleClasses = { "LabelSubText" } });
    }
}
