using System.Text;
using Content.Client._CMU14.Localizations;
using Content.Shared._CMU14.Round.Objectives;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._CMU14.Round.Objectives;

[GenerateTypedNameReferences]
public sealed partial class ObjectiveEntryControl : Control
{
    public ObjectiveEntryControl()
    {
        RobustXamlLoader.Load(this);
    }

    public void SetData(ObjectiveEntry obj, Action<string> requestIntel)
    {
        var typeBack = (StyleBoxFlat)TypeBadgeBack.PanelOverride!;
        string typeText;
        Color typeColor;
        switch (obj.Type)
        {
            case ObjectiveTypeDisplay.Major:
                typeText = CMULocExtension.GetString("cmu-objective-type-major", "MAJOR");
                typeColor = Color.FromHex("#3A6EA5");
                break;
            case ObjectiveTypeDisplay.Win:
                typeText = CMULocExtension.GetString("cmu-objective-type-final", "FINAL"); // top-tier objective, not victory cond
                typeColor = Color.FromHex("#7A3FA0");
                break;
            default:
                typeText = CMULocExtension.GetString("cmu-objective-type-minor", "MINOR");
                typeColor = Color.FromHex("#5A5A5A");
                break;
        }
        typeBack.BackgroundColor = typeColor;
        TypeBadgeLabel.Text = typeText;
        TypeBadgeLabel.FontColorOverride = Color.White;

        DescriptionLabel.Text = obj.Description;

        string statusText;
        Color statusColor;
        switch (obj.Status)
        {
            case ObjectiveStatusDisplay.Completed:
                statusText = CMULocExtension.GetString("cmu-objective-status-completed", "Completed");
                statusColor = Color.Lime;
                break;
            case ObjectiveStatusDisplay.Failed:
                statusText = CMULocExtension.GetString("cmu-objective-status-failed", "Failed");
                statusColor = Color.Red;
                break;
            case ObjectiveStatusDisplay.Captured:
                statusText = CMULocExtension.GetString("cmu-objective-status-captured", "Captured");
                statusColor = Color.Cyan;
                break;
            case ObjectiveStatusDisplay.Uncaptured:
                statusText = CMULocExtension.GetString("cmu-objective-status-uncaptured", "Uncaptured");
                statusColor = Color.Orange;
                break;
            default:
                statusText = CMULocExtension.GetString("cmu-objective-status-uncompleted", "Uncompleted");
                statusColor = Color.Gold;
                break;
        }
        var statusBack = (StyleBoxFlat)StatusBadgeBack.PanelOverride!;
        statusBack.BackgroundColor = statusColor;
        StatusBadgeLabel.Text = statusText;
        StatusBadgeLabel.FontColorOverride = Color.Black;

        var back = (StyleBoxFlat)Background.PanelOverride!;
        back.BorderColor = statusColor;

        var details = new StringBuilder();
        void AppendDetail(string text)
        {
            if (details.Length > 0)
                details.Append("   •   ");
            details.Append(text);
        }

        if (obj.Repeating)
            AppendDetail(CMULocExtension.GetString("cmu-objective-detail-repeating", "Repeating"));
        if (!string.IsNullOrEmpty(obj.Progress))
            AppendDetail(obj.Progress);
        if (obj.MaxRepeatable is { } maxRepeat and > 0)
        {
            AppendDetail(obj.RepeatsCompleted is { } repeats
                ? CMULocExtension.GetString(
                    "cmu-objective-detail-completed-times",
                    $"Completed {repeats}/{maxRepeat} times",
                    ("completed", repeats),
                    ("maximum", maxRepeat))
                : CMULocExtension.GetString(
                    "cmu-objective-detail-can-complete-times",
                    $"Can be completed {maxRepeat} times",
                    ("maximum", maxRepeat)));
        }
        else if (obj.RepeatsCompleted is { } repeatsOnly and > 0)
        {
            AppendDetail(CMULocExtension.GetString(
                "cmu-objective-detail-times-completed",
                $"Times completed: {repeatsOnly}",
                ("completed", repeatsOnly)));
        }
        if (obj.Points > 0)
            AppendDetail(CMULocExtension.GetString(
                "cmu-objective-detail-worth-points",
                $"Worth {obj.Points} points",
                ("points", obj.Points)));

        DetailsLabel.Text = details.ToString();

        IntelButton.OnPressed += _ => requestIntel(obj.Id);
    }
}
