using Robust.Client.UserInterface.XAML;
using Robust.Client.AutoGenerated;
using Content.Client._CMU14.Localizations;
using Content.Shared._CMU14.Round.Objectives;
using Content.Client.UserInterface.Controls;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;

namespace Content.Client._CMU14.Round.Objectives;

[GenerateTypedNameReferences]
public sealed partial class ObjectiveIntelWindow : FancyWindow
{
    public ObjectiveIntelWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void Populate(
        string objectiveId,
        string defaultTitle,
        List<ObjectiveIntelTierEntry>? tiers,
        int unlockedTier,
        int factionPoints,
        Action<int>? unlockCallback = null)
    {
        Title = CMULocExtension.GetString("cmu-objective-intel-window-title", "Intel Window");

        tiers ??= new List<ObjectiveIntelTierEntry>();
        if (unlockedTier < 0) unlockedTier = 0;
        if (unlockedTier > tiers.Count) unlockedTier = tiers.Count;

        ObjectiveIntelTitle.Text = $" {defaultTitle} ";
        var nextTier = unlockedTier >= tiers.Count
            ? CMULocExtension.GetString(
                "cmu-objective-intel-all-tiers-unlocked",
                "All tiers unlocked")
            : unlockedTier + "/" + tiers.Count;
        nexttierlabel.Text = CMULocExtension.GetString(
            "cmu-objective-intel-next-tier",
            $"Next tier: {nextTier}",
            ("tier", nextTier));
        FactionPointsLabel.Text = factionPoints.ToString();

        UnlockedBox.DisposeAllChildren();
        NextBox.DisposeAllChildren();

        for (int i = 0; i < unlockedTier && i < tiers.Count; i++)
        {
            var tier = tiers[i];
            var (card, body) = CreateCard();
            body.AddChild(new Label { Text = tier.Title, FontColorOverride = Color.FromHex("#4CD137") });
            body.AddChild(new Label { Text = tier.Description });
            UnlockedBox.AddChild(card);
        }

        if (unlockedTier >= tiers.Count)
        {
            var all = new Label
            {
                Text = CMULocExtension.GetString(
                    "cmu-objective-intel-all-tiers-unlocked-message",
                    "All intel tiers unlocked."),
                HorizontalAlignment = HAlignment.Center,
            };
            NextBox.AddChild(all);
        }
        else if (unlockedTier < tiers.Count)
        {
            var nextTierEntry = tiers[unlockedTier];
            var (card, body) = CreateCard();
            body.AddChild(new Label { Text = nextTierEntry.Title });
            if (!string.IsNullOrEmpty(nextTierEntry.Description))
                body.AddChild(new Label { Text = nextTierEntry.Description, FontColorOverride = Color.FromHex("#AAAAAA") });

            var unlockBtn = new Button
            {
                Text = CMULocExtension.GetString(
                    "cmu-objective-intel-unlock-cost",
                    $"Unlock: [{nextTierEntry.CostToUnlock}]",
                    ("cost", nextTierEntry.CostToUnlock)),
                Disabled = unlockCallback == null,
                Margin = new Thickness(0, 4, 0, 0),
            };
            if (unlockCallback != null)
            {
                var idx = unlockedTier;
                unlockBtn.OnPressed += _ => unlockCallback(idx);
            }
            body.AddChild(unlockBtn);
            NextBox.AddChild(card);
        }
    }

    private static (PanelContainer Card, BoxContainer Body) CreateCard()
    {
        var card = new PanelContainer
        {
            PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = Color.FromHex("#1B1B1B"),
                BorderColor = Color.FromHex("#3A3A3A"),
                BorderThickness = new Thickness(1),
            },
        };
        var body = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Vertical, Margin = new Thickness(8, 6) };
        card.AddChild(body);
        return (card, body);
    }
}
