using System.Linq;
using System.Numerics;
using Content.Client._CMU14.Localizations;
using Content.Shared._CMU14.Localizations;
using Content.Shared._AU14.Radio;
using Content.Shared.Radio;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.IoC;
using Robust.Shared.Localization;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;

namespace Content.Client._AU14.Radio;

[GenerateTypedNameReferences]
public sealed partial class ANPRCRadioWindow : DefaultWindow
{
    [Dependency] private IPrototypeManager _prototype = default!;
    [Dependency] private ILocalizationManager _localization = default!;

    public event Action<int>? OnSelectSlot;
    public event Action? OnTogglePower;
    public event Action? OnToggleMonitor;
    public event Action<RadioMode>? OnSetMode;
    public event Action<bool>? OnSetScan;
    public event Action<RadioTxPower>? OnSetTxPower;
    public event Action<int>? OnSetSquelch;
    public event Action<string>? OnSetCallsign;
    public event Action<string>? OnAddSlot;
    public event Action<int>? OnDeleteSlot;
    public event Action<int, ProtoId<RadioChannelPrototype>>? OnSetSlotChannel;
    public event Action<int>? OnClearSlot;
    public event Action? OnCryptoZeroize;
    public event Action? OnCryptoDestroy;
    public event Action? OnCryptoRecrypto;
    public event Action? OnRadioCheck;
    public event Action? OnOpenDirectory;
    public event Action<int, string>? OnManualFrequency;
    public event Action<bool>? OnSetSweep;
    public event Action<int, int>? OnTuneContact;
    public event Action<bool>? OnPrintLog;

    private static readonly Color LcdBright = Color.FromHex("#3FCF8E");
    private static readonly Color LcdMid = Color.FromHex("#2D9E60");
    private static readonly Color LcdDim = Color.FromHex("#4A7A55");
    private static readonly Color LcdOff = Color.FromHex("#1E4A2E");
    private static readonly Color LcdWarning = Color.FromHex("#D6B85A");

    private static readonly Color TextBright = Color.FromHex("#C8D2E8");
    private static readonly Color TextDim = Color.FromHex("#687A9A");
    private static readonly Color TextGood = Color.FromHex("#78D69B");
    private static readonly Color TextWarn = Color.FromHex("#D6B85A");
    private static readonly Color TextBad = Color.FromHex("#D65A5A");
    private static readonly Color TextLog = Color.FromHex("#3FCF8E");

    private ANPRCRadioState? _lastState;

    // the BUI rebuilds this window every open, remember the operator's size for the
    // session so they aren't re-dragging it to fit their screen each time
    private static Vector2? _rememberedSize;

    private bool _recryptoArmed;
    private DateTime _recryptoArmedUntil;

    private int _entryTargetSlot = -1;

    private enum EntryTab { Freq, Net }
    private EntryTab _activeEntryTab = EntryTab.Freq;

    private string? _netLogChannelFilter;
    private string _netLogSearchFilter = string.Empty;
    private readonly List<string> _netLogChannels = new();

    private readonly List<string> _callsignPresets = new();

    public ANPRCRadioWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        Title = Loc.GetString("anprc-window-title");

        PowerButton.OnPressed += _ => OnTogglePower?.Invoke();

        ModeButton.OnPressed += _ =>
        {
            if (_lastState == null) return;
            var next = _lastState.Mode switch
            {
                RadioMode.FrequencyHopping => RadioMode.SingleChannel,
                RadioMode.SingleChannel => RadioMode.CipherText,
                RadioMode.CipherText => RadioMode.PlainText,
                RadioMode.PlainText => RadioMode.FrequencyHopping,
                _ => RadioMode.FrequencyHopping,
            };
            OnSetMode?.Invoke(next);
        };

        MonitorButton.OnPressed += _ => OnToggleMonitor?.Invoke();

        ScanButton.OnPressed += _ =>
        {
            if (_lastState == null) return;
            OnSetScan?.Invoke(!_lastState.ScanEnabled);
        };

        SquelchButton.OnPressed += _ =>
        {
            if (_lastState == null) return;
            var next = _lastState.SquelchLevel >= ANPRCRadioComponent.MaxSquelchLevel ? 0 : _lastState.SquelchLevel + 1;
            OnSetSquelch?.Invoke(next);
        };

        TxPowerButton.OnPressed += _ =>
        {
            if (_lastState == null) return;
            var next = _lastState.TxPower switch
            {
                RadioTxPower.Low => RadioTxPower.Medium,
                RadioTxPower.Medium => RadioTxPower.High,
                _ => RadioTxPower.Low,
            };
            OnSetTxPower?.Invoke(next);
        };

        CallsignSetButton.OnPressed += _ =>
        {
            var text = CallsignLineEdit.Text.Trim().ToUpperInvariant();
            if (text.Length > ANPRCRadioComponent.MaxCallsignLength)
                text = text[..ANPRCRadioComponent.MaxCallsignLength];
            OnSetCallsign?.Invoke(text);
            CallsignLineEdit.Text = string.Empty;
        };

        // picking a preset just fills the line edit, SET still confirms and the field
        // stays free-text for custom callsigns
        CallsignPresetButton.OnItemSelected += args =>
        {
            CallsignPresetButton.SelectId(0);

            if (args.Id <= 0 || args.Id > _callsignPresets.Count)
                return;

            CallsignLineEdit.Text = _callsignPresets[args.Id - 1];
        };

        AddSlotButton.OnPressed += _ =>
        {
            AddSlotPanel.Visible = true;
            AddSlotLabelEdit.Text = string.Empty;
            AddSlotLabelEdit.GrabKeyboardFocus();
        };

        AddSlotConfirmButton.OnPressed += _ =>
        {
            var label = AddSlotLabelEdit.Text.Trim().ToUpperInvariant();
            if (label.Length > ANPRCRadioComponent.MaxLabelLength)
                label = label[..ANPRCRadioComponent.MaxLabelLength];
            if (string.IsNullOrWhiteSpace(label)) label = "NET";
            OnAddSlot?.Invoke(label);
            AddSlotPanel.Visible = false;
            AddSlotLabelEdit.Text = string.Empty;
        };

        AddSlotCancelButton.OnPressed += _ =>
        {
            AddSlotPanel.Visible = false;
            AddSlotLabelEdit.Text = string.Empty;
        };

        EntryTabFreqButton.OnPressed += _ => ShowEntryTab(EntryTab.Freq);
        EntryTabNetButton.OnPressed += _ => ShowEntryTab(EntryTab.Net);

        EntryTabClearButton.OnPressed += _ =>
        {
            if (_entryTargetSlot < 0) return;
            OnClearSlot?.Invoke(_entryTargetSlot);
            CloseSlotEntryPanel();
        };

        EntryFreqConfirmButton.OnPressed += _ =>
        {
            if (_entryTargetSlot < 0) return;
            var text = EntryFreqLineEdit.Text.Trim();
            if (!string.IsNullOrEmpty(text))
                OnManualFrequency?.Invoke(_entryTargetSlot, text);
            CloseSlotEntryPanel();
        };

        SlotEntryCloseButton.OnPressed += _ => CloseSlotEntryPanel();

        ZeroizeButton.OnPressed += _ => OnCryptoZeroize?.Invoke();
        DestroyButton.OnPressed += _ => OnCryptoDestroy?.Invoke();

        // superseding every fill card in the faction is not a one-misclick action:
        // first press arms the button, a second press within the window confirms
        RecryptoButton.Text = Loc.GetString("anprc-recrypto-button");
        RecryptoButton.OnPressed += _ =>
        {
            if (_recryptoArmed && DateTime.UtcNow <= _recryptoArmedUntil)
            {
                DisarmRecrypto();
                OnCryptoRecrypto?.Invoke();
                return;
            }

            _recryptoArmed = true;
            _recryptoArmedUntil = DateTime.UtcNow + TimeSpan.FromSeconds(4);
            RecryptoButton.Text = Loc.GetString("anprc-recrypto-button-confirm");
            RecryptoButton.ModulateSelfOverride = TextBad;
        };

        RadioCheckButton.OnPressed += _ => OnRadioCheck?.Invoke();
        DirectoryButton.OnPressed += _ => OnOpenDirectory?.Invoke();

        SweepButton.OnPressed += _ =>
        {
            if (_lastState == null) return;
            OnSetSweep?.Invoke(!_lastState.SweepEnabled);
        };

        PrintLogButton.OnPressed += _ => OnPrintLog?.Invoke(false);
        PrintInterceptsButton.OnPressed += _ => OnPrintLog?.Invoke(true);

        NetLogChannelFilter.OnItemSelected += args =>
        {
            NetLogChannelFilter.SelectId(args.Id);
            _netLogChannelFilter = args.Id == 0 ? null : _netLogChannels[args.Id - 1];
            if (_lastState != null)
                RebuildNetLog(_lastState);
        };

        NetLogSearchEdit.OnTextChanged += args =>
        {
            _netLogSearchFilter = args.Text.Trim();
            if (_lastState != null)
                RebuildNetLog(_lastState);
        };

        NetLogFilterClearButton.OnPressed += _ =>
        {
            _netLogChannelFilter = null;
            _netLogSearchFilter = string.Empty;
            NetLogSearchEdit.Text = string.Empty;

            // the dropdown is empty until the first state arrives, and selecting an
            // id it does not carry throws rather than no-opping
            if (NetLogChannelFilter.ItemCount > 0)
                NetLogChannelFilter.SelectId(0);
            if (_lastState != null)
                RebuildNetLog(_lastState);
        };

        AddSlotPanel.Visible = false;
        SlotEntryPanel.Visible = false;
    }

    // clamp to the viewport so the panel never opens taller than a small screen, and
    // restore the size the operator last dragged it to
    protected override void EnteredTree()
    {
        base.EnteredTree();

        var target = _rememberedSize ?? SetSize;

        if (Root is { } root)
            target = Vector2.Min(target, root.Size * 0.95f);

        SetSize = Vector2.Max(target, new Vector2(MinWidth, MinHeight));
    }

    protected override void Resized()
    {
        base.Resized();

        if (IsInsideTree)
            _rememberedSize = Size;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (_recryptoArmed && DateTime.UtcNow > _recryptoArmedUntil)
            DisarmRecrypto();
    }

    private void DisarmRecrypto()
    {
        _recryptoArmed = false;
        RecryptoButton.Text = Loc.GetString("anprc-recrypto-button");
        RecryptoButton.ModulateSelfOverride = null;
    }

    public void UpdateState(ANPRCRadioState state)
    {
        _lastState = state;

        var hasActiveDynFreq = state.FrequencyOverrides.TryGetValue(state.ActiveSlot, out var activeDynFreq);
        RadioChannelPrototype? activeProto = null;
        var hasActiveChannel = !hasActiveDynFreq &&
                               state.Presets.TryGetValue(state.ActiveSlot, out var activeChannel) &&
                               _prototype.TryIndex(activeChannel, out activeProto);

        var hasAnyActive = hasActiveChannel || hasActiveDynFreq;
        // planted retrans stations are fully operable from the panel without being worn
        var deployed = state.IsEquipped || state.Planted;
        var online = state.Enabled && deployed;
        var ready = online && hasAnyActive && state.ActiveSlot >= 0;

        HeaderPowerLabel.Text = state.Enabled
            ? Ui("cmu-anprc-ui-power-on", "PWR: ON")
            : Ui("cmu-anprc-ui-power-off", "PWR: OFF");
        HeaderPowerLabel.FontColorOverride = state.Enabled ? TextGood : TextBad;

        if (state.Planted)
        {
            HeaderLinkLabel.Text = Ui("cmu-anprc-ui-link-retrans", "LINK: RETRANS");
            HeaderLinkLabel.FontColorOverride = state.Enabled ? TextGood : TextDim;
        }
        else if (!state.IsEquipped)
        {
            HeaderLinkLabel.Text = Ui("cmu-anprc-ui-link-not-worn", "LINK: NOT WORN");
            HeaderLinkLabel.FontColorOverride = TextWarn;
        }
        else if (!state.Enabled)
        {
            HeaderLinkLabel.Text = Ui("cmu-anprc-ui-link-standby", "LINK: STBY");
            HeaderLinkLabel.FontColorOverride = TextDim;
        }
        else
        {
            HeaderLinkLabel.Text = hasAnyActive
                ? Ui("cmu-anprc-ui-link-ready", "LINK: READY")
                : Ui("cmu-anprc-ui-link-no-net", "LINK: NO NET");
            HeaderLinkLabel.FontColorOverride = hasAnyActive ? TextGood : TextWarn;
        }

        LcdModeLabel.Text = Ui(
            "cmu-anprc-ui-mode",
            $"MODE: {ModeShort(state.Mode)}",
            ("mode", ModeShort(state.Mode)));
        LcdModeLabel.FontColorOverride = online ? LcdDim : LcdOff;
        CryptoLabel.FontColorOverride = online ? LcdDim : LcdOff;

        if (hasActiveDynFreq)
        {
            var fStr = FormatFreq(activeDynFreq);
            FrequencyLabel.Text = fStr;
            ChannelNameLabel.Text = Ui("cmu-anprc-ui-direct-frequency", "DIRECT FREQ");
            ChannelIdLabel.Text = Ui(
                "cmu-anprc-ui-frequency",
                $"FREQ: {fStr}",
                ("frequency", fStr));
            BandLabel.Text = Ui(
                "cmu-anprc-ui-band",
                $"BAND: {BandName(activeDynFreq)}",
                ("band", BandName(activeDynFreq)));
            WaveformLabel.Text = Ui("cmu-anprc-ui-waveform-los", "WF: LOS");

            FrequencyLabel.FontColorOverride = ready ? LcdBright : LcdOff;
            ChannelNameLabel.FontColorOverride = ready ? LcdMid : LcdOff;
            ChannelIdLabel.FontColorOverride = online ? LcdDim : LcdOff;
            BandLabel.FontColorOverride = online ? LcdDim : LcdOff;
            WaveformLabel.FontColorOverride = online ? LcdDim : LcdOff;
        }
        else if (activeProto != null)
        {
            FrequencyLabel.Text = FormatFreq(PlanFreq(activeProto));
            ChannelNameLabel.Text = activeProto.LocalizedName.ToUpperInvariant();
            ChannelIdLabel.Text = Ui(
                "cmu-anprc-ui-channel",
                $"CH: {activeProto.ID}",
                ("channel", activeProto.ID));
            BandLabel.Text = Ui(
                "cmu-anprc-ui-band",
                $"BAND: {BandName(PlanFreq(activeProto))}",
                ("band", BandName(PlanFreq(activeProto))));
            WaveformLabel.Text = Ui(
                "cmu-anprc-ui-waveform",
                $"WF: {(activeProto.LongRange ? "SAT" : "LOS")}",
                ("waveform", activeProto.LongRange ? "SAT" : "LOS"));

            FrequencyLabel.FontColorOverride = ready ? LcdBright : LcdOff;
            ChannelNameLabel.FontColorOverride = ready ? LcdMid : LcdOff;
            ChannelIdLabel.FontColorOverride = online ? LcdDim : LcdOff;
            BandLabel.FontColorOverride = online ? LcdDim : LcdOff;
            WaveformLabel.FontColorOverride = online ? LcdDim : LcdOff;
        }
        else
        {
            FrequencyLabel.Text = "-- . ---";
            ChannelNameLabel.Text = state.ActiveSlot < 0
                ? Ui("cmu-anprc-ui-no-slot-active", "NO SLOT ACTIVE")
                : Ui("cmu-anprc-ui-slot-empty", "SLOT EMPTY");
            ChannelIdLabel.Text = Ui("cmu-anprc-ui-channel-placeholder", "CH: ---");
            BandLabel.Text = Ui("cmu-anprc-ui-band-placeholder", "BAND: ---");
            WaveformLabel.Text = Ui("cmu-anprc-ui-waveform-placeholder", "WF: ---");

            FrequencyLabel.FontColorOverride = LcdOff;
            ChannelNameLabel.FontColorOverride = LcdOff;
            ChannelIdLabel.FontColorOverride = LcdOff;
            BandLabel.FontColorOverride = LcdOff;
            WaveformLabel.FontColorOverride = LcdOff;
        }

        if (!online)
        {
            TxIndicator.FontColorOverride = LcdOff;
            TxLabel.Text = Ui("cmu-anprc-ui-off", "OFF");
            TxLabel.FontColorOverride = LcdOff;
        }
        else if (!hasAnyActive)
        {
            TxIndicator.FontColorOverride = LcdWarning;
            TxLabel.Text = Ui("cmu-anprc-ui-no-net", "NO NET");
            TxLabel.FontColorOverride = LcdWarning;
        }
        else
        {
            TxIndicator.FontColorOverride = LcdBright;
            TxLabel.Text = state.MonitorEnabled
            ? Ui("cmu-anprc-ui-monitor-short", "MON")
            : Ui("cmu-anprc-ui-standby", "STBY");
            TxLabel.FontColorOverride = state.MonitorEnabled ? LcdBright : LcdDim;
        }

        if (!deployed)
        {
            BitStatusLabel.Text = Ui("cmu-anprc-ui-bit-not-seated", "BIT: NOT SEATED");
            BitStatusLabel.FontColorOverride = LcdWarning;
        }
        else if (!state.Enabled)
        {
            BitStatusLabel.Text = Ui("cmu-anprc-ui-bit-offline", "BIT: OFFLINE");
            BitStatusLabel.FontColorOverride = LcdOff;
        }
        else if (!hasAnyActive)
        {
            BitStatusLabel.Text = Ui("cmu-anprc-ui-bit-no-net", "BIT: NO NET");
            BitStatusLabel.FontColorOverride = LcdWarning;
        }
        else
        {
            BitStatusLabel.Text = Ui("cmu-anprc-ui-bit-pass", "BIT: PASS");
            BitStatusLabel.FontColorOverride = LcdBright;
        }

        SignalBarsLabel.Text = Bars(ready ? 8 : 0, 8);
        SignalBarsLabel.FontColorOverride = ready ? LcdBright : LcdOff;

        var batteryFilled = state.HasBattery ? (int)Math.Round(state.BatteryFraction * 6) : 0;
        BatteryBarsLabel.Text = state.HasBattery
            ? Bars(batteryFilled, 6)
            : Ui("cmu-anprc-ui-no-cell", "NO CELL");
        BatteryBarsLabel.FontColorOverride = !state.HasBattery ? TextBad
                                            : state.BatteryFraction <= 0.2f ? LcdWarning
                                            : LcdDim;

        var antenna = CMUPrototypeLocalization.GetLiteralText(
            _localization,
            "ANPRCAntenna",
            "label",
            state.AntennaLabel);
        AntennaLabel.Text = Ui(
            "cmu-anprc-ui-antenna",
            $"ANT: {state.AntennaLabel}",
            ("antenna", antenna));
        AntennaLabel.FontColorOverride = online ? LcdDim : LcdOff;

        if (!deployed)
        {
            FaultLabel.Text = Ui("cmu-anprc-ui-fault-not-worn", "FAULT: NOT WORN");
            FaultLabel.FontColorOverride = TextWarn;
        }
        else if (!state.Enabled)
        {
            FaultLabel.Text = Ui("cmu-anprc-ui-fault-off", "FAULT: OFF");
            FaultLabel.FontColorOverride = TextDim;
        }
        else if (!hasAnyActive)
        {
            FaultLabel.Text = Ui("cmu-anprc-ui-fault-no-net", "FAULT: NO NET");
            FaultLabel.FontColorOverride = TextWarn;
        }
        else
        {
            FaultLabel.Text = Ui("cmu-anprc-ui-fault-none", "FAULT: NONE");
            FaultLabel.FontColorOverride = TextGood;
        }

        // callsign: manual station override > wearer's assigned callsign (AUTO)
        if (!string.IsNullOrEmpty(state.Callsign))
        {
            CallsignDisplayLabel.Text = state.Callsign;
            CallsignDisplayLabel.FontColorOverride = TextGood;
        }
        else if (!string.IsNullOrEmpty(state.WearerCallsign))
        {
            CallsignDisplayLabel.Text = Ui(
                "cmu-anprc-ui-callsign-auto",
                $"{state.WearerCallsign} (AUTO)",
                ("callsign", state.WearerCallsign));
            CallsignDisplayLabel.FontColorOverride = TextGood;
        }
        else
        {
            CallsignDisplayLabel.Text = Ui("cmu-anprc-ui-unknown-station", "UNKNOWN STATION");
            CallsignDisplayLabel.FontColorOverride = TextDim;
        }

        RebuildCallsignPresets(state);

        RebuildSlotList(state);

        var slotCount = state.SlotLabels.Count;
        PresetSummaryLabel.Text = $"{slotCount}/{ANPRCRadioComponent.MaxSlots}";
        PresetSummaryLabel.FontColorOverride = slotCount > 0 ? TextDim : TextWarn;
        AddSlotButton.Disabled = slotCount >= ANPRCRadioComponent.MaxSlots || !online;

        ModeButton.Text = Ui(
            "cmu-anprc-ui-mode-button",
            $"MODE {ModeShort(state.Mode)}",
            ("mode", ModeShort(state.Mode)));
        MonitorButton.Text = state.MonitorEnabled
            ? Ui("cmu-anprc-ui-monitor-on", "MON ON")
            : Ui("cmu-anprc-ui-monitor-off", "MON OFF");
        ScanButton.Text = state.ScanEnabled
            ? Ui("cmu-anprc-ui-scan-on", "SCAN ON")
            : Ui("cmu-anprc-ui-scan-off", "SCAN OFF");
        SquelchButton.Text = Ui(
            "cmu-anprc-ui-squelch",
            $"SQL {state.SquelchLevel}",
            ("level", state.SquelchLevel));
        TxPowerButton.Text = Ui(
            "cmu-anprc-ui-transmit-power",
            $"TX {state.TxPower.Short()}",
            ("power", TxPowerShort(state.TxPower)));

        ModeButton.Disabled = !online;
        MonitorButton.Disabled = !online;
        ScanButton.Disabled = !online;
        SquelchButton.Disabled = !online;
        TxPowerButton.Disabled = !online;
        MonitorButton.Pressed = state.MonitorEnabled && online;
        ScanButton.Pressed = state.ScanEnabled && online;

        RoleValueLabel.Text = state.Planted
            ? Ui("cmu-anprc-ui-retrans-station", "RETRANS STATION")
            : Ui("cmu-anprc-ui-rto-relay", "RTO RELAY");

        RelayValueLabel.Text = online && hasAnyActive
            ? Ui("cmu-anprc-ui-anchor", "ANCHOR")
            : Ui("cmu-anprc-ui-standby", "STBY");
        RelayValueLabel.FontColorOverride = online && hasAnyActive ? TextGood : TextDim;

        DiagnosticLineA.Text = online && hasAnyActive
            ? Ui("cmu-anprc-ui-anchor-active", "ANCHOR: ACTIVE")
            : online
                ? Ui("cmu-anprc-ui-anchor-standby", "ANCHOR: STBY")
                : Ui("cmu-anprc-ui-anchor-offline", "ANCHOR: OFFLINE");
        DiagnosticLineA.FontColorOverride = online && hasAnyActive ? TextGood : TextDim;
        DiagnosticLineB.Text = online && hasAnyActive
            ? Ui("cmu-anprc-ui-bypass-armed", "BYPASS: ARMED")
            : Ui("cmu-anprc-ui-bypass-no", "BYPASS: NO");
        DiagnosticLineB.FontColorOverride = online && hasAnyActive ? TextGood : TextDim;

        RoleValueLabel.FontColorOverride = online ? TextBright : TextDim;

        var hasFill = !string.IsNullOrEmpty(state.CryptoFaction);
        var secured = hasFill && !state.CryptoStale;

        CryptoStatusLabel.Text = secured
            ? Ui(
                "cmu-anprc-ui-secured",
                $"SECURED ({state.CryptoDesignation})",
                ("designation", state.CryptoDesignation))
            : hasFill
                ? Ui(
                    "cmu-anprc-ui-stale",
                    $"STALE ({state.CryptoDesignation})",
                    ("designation", state.CryptoDesignation))
                : Ui("cmu-anprc-ui-unsecured", "UNSECURED");
        CryptoStatusLabel.FontColorOverride = secured ? TextGood : hasFill ? TextWarn : TextBad;

        CryptoFillLabel.Text = hasFill
            ? state.CryptoStale
                ? Ui(
                    "cmu-anprc-ui-fill-superseded",
                    $"FILL: {state.CryptoDesignation} ({state.CryptoFaction.ToUpperInvariant()}) - SUPERSEDED, RECRYPTO REQUIRED",
                    ("designation", state.CryptoDesignation),
                    ("faction", state.CryptoFaction.ToUpperInvariant()))
                : Ui(
                    "cmu-anprc-ui-fill-loaded",
                    $"FILL: {state.CryptoDesignation} ({state.CryptoFaction.ToUpperInvariant()})",
                    ("designation", state.CryptoDesignation),
                    ("faction", state.CryptoFaction.ToUpperInvariant()))
            : Ui("cmu-anprc-ui-fill-none", "FILL: NONE - insert fill card to load");
        CryptoFillLabel.FontColorOverride = secured ? TextGood : hasFill ? TextWarn : TextDim;

        ZeroizeButton.Disabled = !online || !hasFill;
        DestroyButton.Disabled = !online || !hasFill;
        RecryptoButton.Disabled = !online || !secured;

        if (RecryptoButton.Disabled && _recryptoArmed)
            DisarmRecrypto();

        RadioCheckButton.Disabled = !ready;

        RebuildSweep(state);
        RebuildNetLog(state);

        PrintLogButton.Disabled = !online || state.NetLog.Count == 0;
        PrintInterceptsButton.Disabled = !online || state.NetLog.All(e => !e.Intercepted);

        PowerButton.Text = state.Enabled
            ? Loc.GetString("anprc-power-off-button")
            : Loc.GetString("anprc-power-on-button");

        var net = hasActiveDynFreq
            ? Ui(
                "cmu-anprc-ui-direct-net",
                $"DIRECT {FormatFreq(activeDynFreq)}",
                ("frequency", FormatFreq(activeDynFreq)))
            : activeProto?.LocalizedName ?? Ui("cmu-anprc-ui-no-net-sentence", "No net");

        var placement = state.Planted
            ? Ui("cmu-anprc-ui-planted", "PLANTED")
            : state.IsEquipped
                ? Ui("cmu-anprc-ui-equipped", "EQUIPPED")
                : Ui("cmu-anprc-ui-unequipped", "UNEQUIPPED");
        var power = state.Enabled
            ? Ui("cmu-anprc-ui-on", "ON")
            : Ui("cmu-anprc-ui-off", "OFF");
        StatusLabel.Text = Ui(
            "cmu-anprc-ui-footer-status",
            $"{placement} · {power} · {net}",
            ("placement", placement),
            ("power", power),
            ("net", net));
    }

    // only rebuild the dropdown when the pool actually changes, otherwise the periodic
    // state updates yank an open dropdown shut
    private void RebuildCallsignPresets(ANPRCRadioState state)
    {
        if (state.CallsignPresets.SequenceEqual(_callsignPresets))
        {
            CallsignPresetButton.Visible = _callsignPresets.Count > 0;
            return;
        }

        _callsignPresets.Clear();
        _callsignPresets.AddRange(state.CallsignPresets);

        CallsignPresetButton.Clear();
        CallsignPresetButton.AddItem(Ui("cmu-anprc-ui-presets", "PRESETS"), 0);
        for (var i = 0; i < _callsignPresets.Count; i++)
        {
            CallsignPresetButton.AddItem(_callsignPresets[i], i + 1);
        }

        CallsignPresetButton.SelectId(0);
        CallsignPresetButton.Visible = _callsignPresets.Count > 0;
    }

    private void RebuildSlotList(ANPRCRadioState state)
    {
        SlotListContainer.RemoveAllChildren();

        // planted retrans stations stay tunable from the panel, matching the
        // deployed logic above, so nobody has to pack the bag up to switch nets
        var online = state.Enabled && (state.IsEquipped || state.Planted);
        var sortedSlots = state.SlotLabels.Keys.OrderBy(k => k).ToList();

        foreach (var slot in sortedSlots)
        {
            var label = GetSlotLabel(state.SlotLabels[slot]);
            var isActive = slot == state.ActiveSlot;

            string freqText;
            if (state.FrequencyOverrides.TryGetValue(slot, out var dynFreq))
            {
                // a raw frequency the sweep fixed but could not name reads as an
                // unknown net rather than a plain direct entry, so an operator can
                // tell a tuned intercept from a number they punched in themselves
                var unknownNet = state.SweepContacts.Any(contact =>
                    contact.Resolved && !contact.Known && contact.Frequency == dynFreq);

                freqText = unknownNet
                    ? Ui(
                        "cmu-anprc-ui-frequency-unknown-net",
                        $"{FormatFreq(dynFreq)} MHz · UNKNOWN NET",
                        ("frequency", FormatFreq(dynFreq)))
                    : Ui(
                        "cmu-anprc-ui-frequency-direct",
                        $"{FormatFreq(dynFreq)} MHz · DIRECT",
                        ("frequency", FormatFreq(dynFreq)));
            }
            else if (state.Presets.TryGetValue(slot, out var ch) && _prototype.TryIndex(ch, out var proto))
                freqText = $"{FormatFreq(PlanFreq(proto))} MHz · {proto.LocalizedName.ToUpperInvariant()}";
            else
                freqText = Ui("cmu-anprc-ui-empty", "--- EMPTY ---");

            var row = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal, SeparationOverride = 4 };

            var selectBtn = new Button
            {
                Text = $"[{label}]  {freqText}",
                HorizontalExpand = true,
                Pressed = isActive && online,
                Disabled = !online,
            };
            var capturedSlot = slot;
            selectBtn.OnPressed += _ => OnSelectSlot?.Invoke(capturedSlot);

            var tuneBtn = new Button
            {
                Text = Ui("cmu-anprc-ui-tune", "TUNE"),
                MinWidth = 52,
                Disabled = !online,
            };
            tuneBtn.OnPressed += _ => OpenSlotEntryPanel(capturedSlot, state);

            var delBtn = new Button
            {
                Text = Ui("cmu-anprc-ui-delete-short", "DEL"),
                MinWidth = 44,
            };
            delBtn.OnPressed += _ => OnDeleteSlot?.Invoke(capturedSlot);

            row.AddChild(selectBtn);
            row.AddChild(tuneBtn);
            row.AddChild(delBtn);
            SlotListContainer.AddChild(row);
        }
    }

    private void OpenSlotEntryPanel(int slot, ANPRCRadioState state)
    {
        _entryTargetSlot = slot;
        var label = state.SlotLabels.TryGetValue(slot, out var lbl)
            ? GetSlotLabel(lbl)
            : $"P{slot + 1}";
        SlotEntryHeaderLabel.Text = Ui(
            "cmu-anprc-ui-tune-slot-label",
            $"TUNE [{label}]:",
            ("label", label));
        SlotEntryPanel.Visible = true;
        EntryFreqLineEdit.Text = string.Empty;
        ShowEntryTab(EntryTab.Freq);
        RebuildNetList(state);
    }

    private void CloseSlotEntryPanel()
    {
        SlotEntryPanel.Visible = false;
        _entryTargetSlot = -1;
        EntryFreqLineEdit.Text = string.Empty;
    }

    private void ShowEntryTab(EntryTab tab)
    {
        _activeEntryTab = tab;
        EntryFreqPanel.Visible = tab == EntryTab.Freq;
        EntryNetScroll.Visible = tab == EntryTab.Net;

        EntryTabFreqButton.Pressed = tab == EntryTab.Freq;
        EntryTabNetButton.Pressed = tab == EntryTab.Net;
    }


    // frequencies come from the round's signal plan carried in the BUI state,
    // the prototype value is only the fallback book number
    private int PlanFreq(RadioChannelPrototype proto)
    {
        return _lastState != null && _lastState.ChannelFrequencies.TryGetValue(proto.ID, out var freq)
            ? freq
            : proto.Frequency;
    }

    private string GetSlotLabel(string label)
    {
        return CMUPrototypeLocalization.GetLiteralOverrideOrFallback(
            _localization,
            "ANPRCRadio",
            "label",
            label);
    }

    private void RebuildNetList(ANPRCRadioState state)
    {
        EntryNetList.RemoveAllChildren();

        var opFaction = state.OperatorFaction;

        foreach (var proto in _prototype.EnumeratePrototypes<RadioChannelPrototype>())
        {
            // skip sentinels and non-displayable channels
            if (proto.Frequency <= 0)
                continue;

            // own-faction nets always list. a foreign net lists once the search
            // receiver has fixed it - the server only puts a foreign channel's
            // frequency in the state after it lands in DiscoveredFrequencies.
            // faction-less channels (colony, civilian) get tuned by raw frequency
            var ownNet = string.IsNullOrEmpty(opFaction) ||
                         string.Equals(proto.Faction, opFaction, StringComparison.OrdinalIgnoreCase);

            var discovered = !ownNet &&
                             !string.IsNullOrEmpty(proto.Faction) &&
                             state.ChannelFrequencies.ContainsKey(proto.ID);

            if (!ownNet && !discovered)
                continue;

            var capturedProto = proto;
            var btn = new Button
            {
                Text = discovered
                    ? Ui(
                        "cmu-anprc-ui-net-list-intercept",
                        $"{proto.LocalizedName.ToUpperInvariant()}  -  {FormatFreq(PlanFreq(proto))} MHz · INTERCEPT",
                        ("name", proto.LocalizedName.ToUpperInvariant()),
                        ("frequency", FormatFreq(PlanFreq(proto))))
                    : Ui(
                        "cmu-anprc-ui-net-list-entry",
                        $"{proto.LocalizedName.ToUpperInvariant()}  -  {FormatFreq(PlanFreq(proto))} MHz",
                        ("name", proto.LocalizedName.ToUpperInvariant()),
                        ("frequency", FormatFreq(PlanFreq(proto)))),
                HorizontalExpand = true,
            };
            btn.OnPressed += _ =>
            {
                if (_entryTargetSlot < 0) return;
                OnSetSlotChannel?.Invoke(_entryTargetSlot, new ProtoId<RadioChannelPrototype>(capturedProto.ID));
                CloseSlotEntryPanel();
            };
            EntryNetList.AddChild(btn);
        }
    }

    private void RebuildSweep(ANPRCRadioState state)
    {
        var online = state.Enabled && (state.IsEquipped || state.Planted);

        SweepButton.Disabled = !online;
        SweepButton.Text = state.SweepEnabled
            ? Ui("cmu-anprc-ui-stop-search", "STOP SEARCH")
            : Ui("cmu-anprc-ui-start-search", "START SEARCH");
        SweepButton.Pressed = state.SweepEnabled && online;

        SweepStatusLabel.Text = !online
            ? Ui("cmu-anprc-ui-offline", "OFFLINE")
            : state.SweepEnabled
                ? Ui("cmu-anprc-ui-searching", "SEARCHING")
                : Ui("cmu-anprc-ui-idle", "IDLE");
        SweepStatusLabel.FontColorOverride = state.SweepEnabled && online ? TextWarn : TextDim;

        if (state.SweepEnabled && online)
        {
            SweepBandLabel.Text = Ui(
                "cmu-anprc-ui-search-head",
                $"HEAD: {FormatFreq(state.SweepPosition)} MHz",
                ("frequency", FormatFreq(state.SweepPosition)));
            SweepBandLabel.FontColorOverride = LcdBright;
            SweepHintLabel.Text = Ui("cmu-anprc-ui-nets-dropped", "NETS DROPPED · TX INHIBITED");
            SweepHintLabel.FontColorOverride = TextWarn;
        }
        else
        {
            SweepBandLabel.Text = Ui("cmu-anprc-ui-band-idle", "BAND IDLE");
            SweepBandLabel.FontColorOverride = LcdOff;
            SweepHintLabel.Text = Ui(
                "cmu-anprc-ui-search-warning",
                "Searching drops all nets and blocks transmit.");
            SweepHintLabel.FontColorOverride = TextDim;
        }

        SweepContactList.RemoveAllChildren();

        if (state.SweepContacts.Count == 0)
        {
            SweepContactList.AddChild(new Label
            {
                Text = Ui("cmu-anprc-ui-no-contacts", "NO CONTACTS"),
                FontColorOverride = TextDim,
            });

            return;
        }

        foreach (var contact in state.SweepContacts)
        {
            var row = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                SeparationOverride = 4,
            };

            if (contact.Resolved)
            {
                // an own net is dimmed and tagged: it is on the band, but it was never
                // work, and it should not read like a prize the operator won
                row.AddChild(new Label
                {
                    Text = contact.Known
                        ? Ui(
                            "cmu-anprc-ui-contact-own-net",
                            $"{FormatFreq(contact.Frequency)} MHz · {contact.ChannelName.ToUpperInvariant()} · OWN NET",
                            ("frequency", FormatFreq(contact.Frequency)),
                            ("name", contact.ChannelName.ToUpperInvariant()))
                        : Ui(
                            "cmu-anprc-ui-contact",
                            $"{FormatFreq(contact.Frequency)} MHz · {contact.ChannelName.ToUpperInvariant()}",
                            ("frequency", FormatFreq(contact.Frequency)),
                            ("name", contact.ChannelName.ToUpperInvariant())),
                    FontColorOverride = contact.Known ? TextDim : TextGood,
                    HorizontalExpand = true,
                    ClipText = true,
                });

                // own nets are already sitting in the operator's presets, so only a
                // fixed foreign net gets the shortcut
                if (!contact.Known)
                {
                    var tuneBtn = new Button
                    {
                        Text = Ui("cmu-anprc-ui-tune", "TUNE"),
                        MinWidth = 52,
                        Disabled = state.ActiveSlot < 0 || !state.SlotLabels.ContainsKey(state.ActiveSlot),
                    };

                    var captured = contact.Frequency;
                    var slot = state.ActiveSlot;
                    tuneBtn.OnPressed += _ => OnTuneContact?.Invoke(slot, captured);

                    row.AddChild(tuneBtn);
                }
            }
            else
            {
                // partial fix: only the digits earned so far, the rest still masked
                row.AddChild(new Label
                {
                    Text = Ui(
                        "cmu-anprc-ui-contact-partial",
                        $"~{MaskDigits(FormatFreq(contact.Frequency), contact.Tier, contact.TierMax)} MHz · PARTIAL {contact.Tier}/{contact.TierMax}",
                        ("frequency", MaskDigits(FormatFreq(contact.Frequency), contact.Tier, contact.TierMax)),
                        ("tier", contact.Tier),
                        ("maximum", contact.TierMax)),
                    FontColorOverride = TextWarn,
                    HorizontalExpand = true,
                    ClipText = true,
                });
            }

            SweepContactList.AddChild(row);
        }
    }

    private void RebuildNetLog(ANPRCRadioState state)
    {
        RebuildNetLogChannelFilter(state);

        NetLogContainer.RemoveAllChildren();

        var shown = 0;
        foreach (var entry in state.NetLog)
        {
            if (!NetLogEntryMatchesFilters(entry))
                continue;

            shown++;
            var ts = TimeSpan.FromSeconds(entry.Timestamp);
            var timeStr = $"{(int) ts.TotalMinutes:D2}:{ts.Seconds:D2}";

            var line = new Label
            {
                Text = entry.Intercepted
                    ? Ui(
                        "cmu-anprc-ui-log-entry-intercept",
                        $"[{timeStr}] {entry.SenderName} · {entry.ChannelDisplay} · INTERCEPT",
                        ("time", timeStr),
                        ("sender", entry.SenderName),
                        ("channel", entry.ChannelDisplay))
                    : Ui(
                        "cmu-anprc-ui-log-entry",
                        $"[{timeStr}] {entry.SenderName} · {entry.ChannelDisplay}",
                        ("time", timeStr),
                        ("sender", entry.SenderName),
                        ("channel", entry.ChannelDisplay)),
                FontColorOverride = entry.Intercepted ? TextWarn : TextLog,
                ClipText = true,
            };
            var msg = new Label
            {
                Text = $"  {entry.Message}",
                FontColorOverride = TextDim,
                ClipText = true,
            };
            NetLogContainer.AddChild(line);
            NetLogContainer.AddChild(msg);
        }

        var filtered = _netLogChannelFilter != null || _netLogSearchFilter.Length > 0;
        NetLogCountLabel.Text = filtered
            ? Ui(
                "cmu-anprc-ui-filtered-entry-count",
                $"{shown}/{state.NetLog.Count} entries",
                ("shown", shown),
                ("total", state.NetLog.Count))
            : Ui(
                "cmu-anprc-ui-entry-count",
                $"{state.NetLog.Count} entries",
                ("count", state.NetLog.Count));

        if (filtered && shown == 0 && state.NetLog.Count > 0)
        {
            NetLogContainer.AddChild(new Label
            {
                Text = Ui("cmu-anprc-ui-no-filter-matches", "NO ENTRIES MATCH FILTER"),
                FontColorOverride = TextDim,
            });
        }
    }

    private bool NetLogEntryMatchesFilters(ANPRCNetLogEntry entry)
    {
        if (_netLogChannelFilter != null && entry.ChannelDisplay != _netLogChannelFilter)
            return false;

        return _netLogSearchFilter.Length == 0 ||
               entry.SenderName.Contains(_netLogSearchFilter, StringComparison.OrdinalIgnoreCase) ||
               entry.Message.Contains(_netLogSearchFilter, StringComparison.OrdinalIgnoreCase);
    }

    // same deal as the callsign dropdown, only rebuild when the set of nets in the log
    // changes so an open dropdown doesn't get yanked shut
    private void RebuildNetLogChannelFilter(ANPRCRadioState state)
    {
        var channels = state.NetLog
            .Select(e => e.ChannelDisplay)
            .Distinct()
            .OrderBy(c => c, StringComparer.OrdinalIgnoreCase)
            .ToList();

        // on a fresh window with an empty log both lists are empty, so the equality
        // check alone would skip the build and leave the dropdown with no ALL NETS
        // entry for the clear button to select back to
        if (NetLogChannelFilter.ItemCount > 0 && channels.SequenceEqual(_netLogChannels))
            return;

        _netLogChannels.Clear();
        _netLogChannels.AddRange(channels);

        NetLogChannelFilter.Clear();
        NetLogChannelFilter.AddItem(Ui("cmu-anprc-ui-all-nets", "ALL NETS"), 0);
        for (var i = 0; i < _netLogChannels.Count; i++)
        {
            NetLogChannelFilter.AddItem(_netLogChannels[i], i + 1);
        }

        // reselect the previously chosen net, if it rotated out of the 50-entry log fall
        // back to ALL instead of filtering on a ghost
        var selectedIdx = _netLogChannelFilter == null ? -1 : _netLogChannels.IndexOf(_netLogChannelFilter);
        if (selectedIdx < 0)
        {
            _netLogChannelFilter = null;
            NetLogChannelFilter.SelectId(0);
        }
        else
        {
            NetLogChannelFilter.SelectId(selectedIdx + 1);
        }
    }

    private static string FormatFreq(int raw)
        => raw >= 1000 ? $"{raw / 1000}.{raw % 1000:D3}" : $"00.{raw:D3}";

    // replace the digits the operator has not earned with X, so a partial fix reads
    // as 2.4XX instead of a falsely precise 2.400
    private static string MaskDigits(string formatted, int tier, int tierMax)
    {
        var unknown = Math.Clamp(tierMax - tier, 0, formatted.Length);

        return unknown > 0
            ? formatted[..^unknown] + new string('X', unknown)
            : formatted;
    }

    private static string BandName(int f)
        => f < 3000 ? "LF" : f < 30000 ? "HF" : f < 88000 ? "VHF" : f < 300000 ? "UHF" : "SHF";

    private static string Bars(int filled, int total)
    {
        filled = Math.Clamp(filled, 0, total);
        return new string('█', filled) + new string('░', total - filled);
    }

    private static string ModeShort(RadioMode m) => m switch
    {
        RadioMode.FrequencyHopping => "FH",
        RadioMode.SingleChannel => "SC",
        RadioMode.CipherText => "CT",
        RadioMode.PlainText => "PT",
        _ => "FH",
    };

    private string TxPowerShort(RadioTxPower power) => power switch
    {
        RadioTxPower.Low => Ui("cmu-anprc-ui-power-low", "LOW"),
        RadioTxPower.High => Ui("cmu-anprc-ui-power-high", "HIGH"),
        _ => Ui("cmu-anprc-ui-power-medium", "MED"),
    };

    private string Ui(
        string key,
        string fallback,
        params (string, object)[] arguments)
    {
        return CMULocExtension.Resolve(_localization, key, fallback, arguments);
    }
}
