using Content.Client._CMU14.Localizations;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._CMU14.Medical.Injuries.Wounds;

[GenerateTypedNameReferences]
public sealed partial class BodyPartPickerWindow : DefaultWindow
{
    public BodyPartPickerWindow()
    {
        RobustXamlLoader.Load(this);
        Title = CMULocExtension.GetString("cmu-body-part-picker-window-title", "Bandage");
    }
}
