lore-examinable-verb-text = Trasfondo
lore-examinable-verb-disabled = Recordar más detalles sobre este objeto.

rmc-lore-examinable-trimax-polarized-shades = La última línea «TactOptix» de TriMax incorpora polarización avanzada y lentes balísticas ligeras capaces de resistir impactos de metralla pequeña. Estas gafas, muy apreciadas por operadores de primera línea y exploradores del espacio profundo, se anuncian como «probadas en combate y aprobadas para la acción». Circulan rumores sobre usuarios afortunados que sobrevivieron a disparos láser a corta distancia gracias al revestimiento multirreflectante, aunque la postura oficial de TriMax es: «Deja de ponerte delante de los láseres».
rmc-lore-examinable-trimex-personal-shades = Estas imitaciones se comercializan como «TriMex», con una «E» para eludir los derechos de autor, y son populares entre viajeros espaciales ahorradores y aspirantes a tipos duros. Las auténticas presumen de una refracción especular patentada que protege contra destellos atómicos, radiación solar y láseres de designación; estas copias baratas apenas detienen los rayos ultravioleta. ¿Y la famosa historia de una pistola láser cuyo disparo rebotó en las originales? Buena suerte encontrando a alguien que crea que estas podrían conseguirlo. Al menos son baratas, y el lema «Ahorra presupuesto y luce genial mientras lo haces» resulta convincente.

rmc-lore-examinable-m3-eod-pattern-heavy-armor = Esta configuración de la emblemática armadura se desarrolló durante la guerra entre la SPP y la UNMC. Nació de la necesidad de ofrecer mayor protección a los técnicos de comunicaciones destinados a tareas EOD durante el conflicto y representa la máxima protección disponible para un marine corriente. Las hombreras y rodilleras se ampliaron considerablemente para cubrir las arterias de cada extremidad. También se desarrolló un forro especial contra esquirlas con la misma tecnología empleada en el chaleco antifragmentos M70, creado por aquella época.
rmc-lore-examinable-armor-xm4-pattern-intel-armor = Perfección AEGIS. El sistema de conciencia del combatiente XM4 combina placas rígidas del estilo M4 con una red de sensores de movimiento distribuidos por el peto. Cuando se conecta a cualquier visor HUD, reproduce los efectos de una unidad detectora de movimiento M314 y mejora la percepción situacional del usuario. Actualmente está siendo probado sobre el terreno por agentes de inteligencia.

rmc-lore-examinable-thirteen-loko = Una rareza en los mercados modernos, Thirteen Loko es un producto genuino de la Tierra. Su nombre nació del consenso general de que solo alguien ligeramente demente estaría dispuesto a beberlo. Esta bebida energética se ha ganado una reputación infame y un considerable grupo de seguidores. Tras una serie de procesos judiciales de Weyland-Yutani, el veneno de cobra desnaturalizado se retiró de la receta, para decepción de sus consumidores.
rmc-lore-examinable-boda = BODA fue diseñada en 2109. Su campaña publicitaria comenzó como un intento de la SPP por ganarse el corazón y la confianza de colonos de toda la galaxia. Poco después, sus inconfundibles expendedoras cian y grandes reservas de la bebida empezaron a aparecer en almacenes de la UN sin un origen claro. Pese a ciertas inquietudes, las pruebas iniciales determinaron que los productos almacenados eran seguros y sorprendentemente populares en catas a ciegas, por lo que se autorizó el uso del extraño excedente de BODA en las colonias vinculadas a la UN. Disfrutó de cierta popularidad antes de caer en el olvido durante las décadas posteriores, a medida que disminuían las reservas.
rmc-lore-examinable-red-hot-bottle = Supuestamente concebida como un sabor intermedio entre el kétchup y la cayena, esta marca picante obtuvo un enorme reconocimiento en las colonias y naves del espacio de la UN. Su adopción repentina y generalizada coincidió, curiosamente, con la retirada casi simultánea de la salsa picante «ULTRA» original.

rmc-lore-examinable-pitchblende = Colonias de todo el sector extraen grandes cantidades de pechblenda, un mineral de uranio. Se utiliza en reactores de fisión obsoletos, armas nucleares y, con mayor frecuencia, munición perforante. Un equipo de investigación financiado por W-Y determinó que el envenenamiento por radiación causado por esta munición es «insignificante».

rmc-lore-examinable-bottle-of-bone-gel = El gel óseo es un análogo biológico y sintético del hueso con consistencia de arcilla. Permite reparar tanto fisuras como fracturas complejas. No debe usarse para sustituir huesos ausentes, pues no reemplaza la médula ósea del organismo. Su uso excesivo en un periodo breve puede causar inmunodeficiencia aguda o anemia.

rmc-lore-examinable-fountain-pen = «Más que una herramienta de escritura, la pluma estilográfica de AEGIS simboliza distinción y autoridad dentro del Cuerpo de Marines de las Naciones Unidas, la UNMC. Es un objeto de legado entregado exclusivamente al personal de mando de mayor rango; cada pluma homenajea el liderazgo y la dedicación de quien la recibe.
    AEGIS, célebre por su tecnología armamentística, adoptó un enfoque distinto al crear esta pieza. Aunque la pluma parezca alejada de su campo habitual, está impregnada de la filosofía de ingeniería de la empresa y encarna precisión, funcionalidad y robustez.
    Los detalles dorados no son simples adornos: identifican estas plumas y distinguen a sus propietarios. El oro se alea meticulosamente con una sustancia metálica duradera para resistir el desgaste diario. Esa resistencia simboliza la tenacidad y perseverancia exigidas al personal de mando de la UNMC.
    Cada pluma incorpora un intrincado mecanismo de cambio de color que permite alternar entre distintas tintas. Inspirado en los avanzados sistemas de adquisición de blancos del armamento de AEGIS, utiliza actuadores miniaturizados y componentes rectificados con precisión para cambiar con suavidad el flujo de tinta. Un simple giro del cuerpo coloca los cartuchos internos en posición con elegancia mecánica, listos para obedecer al usuario.
    Los colores no se eligen al azar. Cada uno representa un escalafón distinto de la UNMC, de modo que el propietario puede escribir con el tono correspondiente a su rango o al de quien recibirá sus órdenes. Es un testimonio silencioso de la autoridad de sus palabras, como si cada trazo resonara por los pasillos del mando de la UNMC.
    Pese a su aspecto ornamentado, la pluma es tan resistente como cualquier arma de AEGIS y refleja el compromiso de la empresa con la fiabilidad y la durabilidad. Sus componentes metálicos resisten la corrosión y garantizan una larga vida incluso bajo las difíciles condiciones que suele afrontar el alto mando de la UNMC.
    La unión de lujo y utilidad, la mezcla de oro y metal, encarna la elegancia conquistada del mando y la fusión de poder y gracia. Es más que un instrumento de escritura: es un emblema de liderazgo y un reconocimiento a la dedicación y fortaleza de quienes lo portan. La pluma estilográfica de AEGIS se alza como monumento a la precisión, integridad y valentía de los oficiales de mayor rango de la UNMC».

rmc-lore-examinable-s5-red-dot-sight = Una mira colimadora para cualquier clima, designada AN/PVQ-64. Incluye un parasol para mejorar la claridad con mucha luz y resistir la intemperie. Compacta y eficaz, parece una maravilla del diseño militar... hasta que descubres que en realidad es un modelo comercial al que simplemente colocaron una designación militar.
rmc-lore-examinable-s6-reflex-sight = Una sencilla mira réflex plegable designada AN/PVG-72, compatible con la mayoría de sistemas de rieles. Voluminosa pero resistente, puede enlazarse con HUD militares para efectuar cálculos limitados del punto de impacto.
rmc-lore-examinable-s8-4x-telescopic-scope = Una mira Armat de potencia intermedia designada óptica AN/PVQ-31 4x. Bastante básica, pero resistente y lo suficientemente funcional... En realidad, unos 780 metros es el límite práctico del cartucho de 10x24 mm.
rmc-lore-examinable-s4-2x-telescopic-mini-scope = Una óptica ligera designada AN/PVQ-45 2x, adecuada para enfrentamientos a corta y media distancia. Se recomienda calibrarla con frecuencia, pues el primer lote de producción tendía a desviarse hacia un lado u otro con el uso continuado.
rmc-lore-examinable-b8-smart-scope = Una óptica experimental de control de tiro que puede enlazarse con sistemas IFF compatibles de determinadas armas, designada mira inteligente XAN/PVG-110. Es una tecnología experimental desarrollada por AEGIS, que asegura haber resuelto todos los problemas notificados anteriormente con falsos negativos de identificación IFF. Comprueba la mira después de cada despliegue, por si acaso.
rmc-lore-examinable-laser-sight = Un módulo láser estándar de espectro visible designado mira láser AN/PEQ-42. Puede instalarse en cualquier arma de fuego con un riel inferior suficientemente grande.
rmc-lore-examinable-xm-vesg-1-flamer-nozzle = La boquilla acoplable XM-VESG-1, generadora experimental de esferas volátiles exotérmicas para la unidad incineradora M240, fue diseñada para que los Marines lanzaran bolas de fuego a trincheras y búnkeres enemigos. Pese al revestimiento de gel y resina, la bola de nafta ardiente se deshace por la resistencia del aire, lo que ha llevado a los Marines a usar el accesorio como lanzador de fuegos artificiales improvisado durante sus permisos.

rmc-lore-examinable-sasos = Una óptica de vanguardia con identificación IFF, diseñada y fabricada para el sistema de arma de apoyo L91 y denominada mira óptica inteligente para armas ligeras L91O1, aunque los tiradores de la RCM la llaman cariñosamente «la Salsa». El modelo de producción se considera una pieza esencial del L91 SWS, pero los primeros prototipos eran peligrosamente poco fiables y fueron muy criticados por sus evaluadores. Por ello, su adopción inicial entre los tiradores de la RCM fue limitada y muchos continuaron usando ópticas estándar de 2x o 4x.

rmc-lore-examinable-hjra-12-extreme-intensity-incendiary-rocket = Este cohete incendiario utiliza una sustancia experimental denominada «R-189» por la SPP. Fue diseñado para fundir fortificaciones y búnkeres, pero el exceso de unidades suministradas hace que se emplee sobre todo contra personal. Cuando se usa para su cometido original, las temperaturas dejan una nube de aire sobrecalentado que impide el avance de las tropas.
rmc-lore-examinable-ar10-assault-rifle = El AR10 fue fabricado inicialmente durante la década de 1950 por la corporación Armalite, adquirida por Weyland-Yutani en 2002. Fue el primer fusil de producción que incorporó numerosas características innovadoras, como un sistema de cierre y portacerrojo accionado por gas. Solo se produjeron 10 000 unidades y Portugal y Sudán fueron los únicos Estados que lo adoptaron. Desde finales del siglo XX, estos fusiles, junto con los mucho más comunes M16 y AR15, han circulado por las regiones menos civilizadas del espacio, sembrando selvas y suelos coloniales con su poco habitual munición con vaina, una rareza desde la introducción de la munición de pulso. El fusil lleva grabada la palabra «Salazar» en un costado.
rmc-lore-examinable-m54c-ap-magazine = A diferencia de los cargadores HEAP estándar, estos proyectiles de reserva no tienen puntas de uranio empobrecido. Sacrifican parte de su carga para reducir el peso, lo que disminuye el daño pero aumenta la capacidad de penetración y la velocidad en boca.

rmc-lore-examinable-xm-88-heavy-rifle = Desarrollado originalmente por AEGIS Armaments para que el gobierno del Estado del Gran Brasil lo empleara contra infantería mecanizada. La plataforma incorpora un sistema informatizado de adquisición de blancos, una matriz de sensores y un cargador automático electrónico. Estas funciones trabajan conjuntamente para degradar y anular la armadura del objetivo con impactos sucesivos. El Almayer recibió una pequeña cantidad de XM88 mientras se preparaba para la operación Swamp Hopper junto a la UNS Nan-Shan.
rmc-lore-examinable-type-64-submachine-gun = El Type 64 no acaba únicamente en manos de soldados de la SPP: también tiene una vida activa entre grupos rebeldes, fuerzas de seguridad corporativas, mercenarios, ejércitos peor equipados y prácticamente cualquier organización intermedia.

rmc-lore-examinable-smart-gun = El sistema de arma inteligente ML66A fue diseñado para proporcionar a los escuadrones de la UNMC la potencia de fuego pesada móvil y la capacidad de lanzar plomo que el campo de batalla moderno ha demostrado necesarias. Emplea tecnologías revolucionarias surgidas de la investigación y el desarrollo de Aegis Armaments para identificar rápidamente objetivos y permite al usuario seleccionar o ignorar frecuencias IFF concretas sobre la marcha.
    Los modelos de la UNMC están vinculados de forma permanente a las frecuencias IFF de las fuerzas de Marines para evitar incidentes de fuego amigo y simplificar el uso del arma inteligente durante el combate. El arma y su arnés también integran varios sensores de seguimiento de movimiento que transmiten directamente al HUD del usuario cualquier movimiento detectado, lo que acelera aún más la adquisición de blancos.
    Aunque existen armas inteligentes más avanzadas, la ML66A ofrece un equilibrio ideal entre coste y prestaciones para unas fuerzas armadas a gran escala como la UNMC. La investigación de las tecnologías IFF necesarias duró varias décadas y fue financiada parcialmente por la UN para asegurarse de ser la primera nación en obtener la prometedora tecnología. Sin embargo, la TSE obtuvo rápidamente variantes propias para los Marines de la Corona Real.

rmc-lore-examinable-m54c-mk2 = El M54C Mk2 de Aegis Armaments es el omnipresente fusil de dotación estándar de la UNMC y la encarnación de un auténtico fusil de la era espacial. La plataforma M54 se creó a partir de décadas de experiencia combatiendo en los nuevos y variados entornos que ofrecía el universo. Resistir los entornos de la Tierra ya no bastaba: un fusil de la era espacial debía soportar los extremos del espacio.
    La plataforma dominó las pruebas de la UNMC gracias a su innovador diseño y al empleo de munición sin vaina. La UNMC encargó rápidamente una gran tirada de M54C Mk1 para obtener experiencia de campo antes de adoptar un nuevo fusil estándar. Aunque seguía siendo eficaz, el uso prolongado reveló los defectos del Mk1: su falta de modularidad y sus cargadores voluminosos daban como resultado un rendimiento mediocre. Aegis no quería perder el contrato y desarrolló enseguida el Mk2.
    El M54C Mk2 mejora el Mk1 principalmente en la compatibilidad con accesorios. Mientras el Mk1 carecía de un sistema normalizado de montaje, el Mk2 admite casi todos los sistemas estándar empleados por la UNMC. Sus grandes cargadores también fueron sustituidos por otros más pequeños y ergonómicos, mejorando los tiempos de recarga y la eficiencia del almacenamiento de munición.
    La eficacia del M54C Mk2 dentro del Cuerpo de Marines ha favorecido su adopción por varios grupos PMC e incluso por algunos equipos coloniales antidisturbios. Su modularidad y las piezas fáciles de sustituir permiten adaptarlo a las necesidades de cualquier organización y hacen posible que un soldado corriente efectúe incluso tareas de mantenimiento avanzadas.

rmc-lore-examinable-ssg-45 = El SSG45 fue desarrollado en respuesta a las quejas persistentes de la seguridad interna y las divisiones PMC de Weyland-Yutani, insatisfechas sobre el terreno con el M54C Mk2 estándar de la UNMC.
    Aunque el M54C era ligero y fácil de fabricar en masa, carecía de la potencia de parada y la durabilidad necesarias para las operaciones intensas y alejadas de la infraestructura que suelen asignarse a los equipos corporativos de WeYa.
    Varias unidades empezaron a convertir sus fusiles de dotación en variantes personalizadas, llamadas extraoficialmente M54C/2, para mejorar el manejo, la penetración y la fiabilidad. Las modificaciones llamaron suficiente atención como para que la división de I+D de Weyland-Yutani iniciara un programa formal destinado a diseñar un fusil específico basado en experiencia de combate real.
    El resultado fue el SSG45, un fusil de asalto pesado y sin vaina, diseñado para entornos hostiles y para imponerse a corta distancia. Incorpora un sistema integrado de mitigación del retroceso, componentes internos reforzados y compatibilidad con ópticas inteligentes y accesorios mejorados. Aunque técnicamente sigue en pruebas de campo, numerosos equipos de seguridad de WeYa destinados en zonas de alto riesgo ya lo han adoptado.
    Los informes indican un buen rendimiento en enfrentamientos prolongados, con únicamente problemas leves de sobrecalentamiento durante el fuego automático sostenido. El equipo de I+D ya trabaja en corregirlos en las siguientes iteraciones.

rmc-lore-examinable-un-flag = Las Naciones Unidas: la nación más próspera del universo. A través de pruebas y sufrimientos, insurgencias y guerras, las Naciones Unidas han unido bajo una misma enseña a los habitantes de la Tierra y de toda la galaxia. Esta enseña.
    Es una nación por la que merece la pena morir. Triunfarás, fracasarás, vivirás y morirás, pero esta bandera resistirá ante todo. Gloria a las Naciones Unidas.

rmc-lore-examinable-ceremonial-sabre = El sable ceremonial, entregado de serie a los comandantes del Cuerpo de Marines de las Naciones Unidas, es más que una reliquia: es un rito. Cada sable, forjado en una aleación compuesta y pulido hasta reflejar como un espejo, se graba con el nombre y la unidad del Marine cuando asciende al mando.
    Aunque se usa principalmente en ceremonias formales y relevos del mando, su hoja es apta para el combate: un recordatorio silencioso de que, en la UNMC, hasta la tradición derrama sangre cuando es necesario.
    Algunos oficiales veteranos llevan sus sables al combate, no por su filo, sino por lo que representan: liderazgo inquebrantable en el oscuro e implacable vacío espacial. El diseño se remonta a las tradiciones navales de la antigua Tierra, llevadas hasta las estrellas con sombrío orgullo.
    Se dice que, si mueres con él en la mano, tu nombre queda grabado aún más profundamente en la historia de la UNMC.

rmc-lore-examinable-fax-machine = La máquina de fax, pese a su origen arcaico, resulta sorprendentemente adecuada para las naciones espaciales modernas.
    Utiliza el revolucionario sistema telefónico interestelar existente para transmitir documentos como señales de audio, que la máquina receptora puede decodificar y convertir de nuevo en el documento original.
    Weyland-Yutani ha patentado la tecnología, por lo que otros modelos de fax son mucho más lentos y menos habituales.
    Se han planteado dudas sobre la seguridad de usar el sistema telefónico para documentos confidenciales, pero Weyland-Yutani promete que su infraestructura es extremadamente segura.

rmc-lore-examniable-orbital-cannon = Tras el uso reiterado de armas nucleares durante operaciones de la UNMC en colonias civiles, que provocó víctimas innecesarias y desastres ecológicos duraderos, la UNMC determinó que hacía falta un arma intermedia entre la artillería convencional y los explosivos nucleares para evitar nuevos incidentes y el rechazo público.
    Varias empresas presentaron prototipos, entre ellos misiles antinave modificados para atacar designaciones láser terrestres y grandes bombas convencionales de baja altitud transportadas por una nave de descenso AUD-25. Finalmente, la UNMC consideró más práctica la propuesta de Aegis Armaments: un enorme cañón de artillería naval de 400 mm capaz de disparar distintos tipos de munición específica.
    La inmensa mayoría de las naves de transporte de tropas de la UNMC recibió estos cañones, proporcionando capacidad de bombardeo orbital a cada compañía de Marines. Tras su éxito generalizado, se crearon modelos nuevos para resolver varios problemas importantes, sobre todo la preocupante frecuencia de incidentes de fuego amigo.
    Los nuevos modelos de cañones orbitales Aegis pueden apuntar y disparar eficazmente proyectiles guiados por láser y GPS de precisión, aumentando mucho la exactitud y reduciendo el riesgo de fuego amigo. Por desgracia, aún no han llegado a las flotas fronterizas peor financiadas, donde los incidentes de fuego amigo durante bombardeos orbitales siguen siendo demasiado frecuentes.

rmc-lore-examinable-lady-fingers = Un atrevido experimento de mercadotecnia: estos brutales cigarrillos mentolados sin filtro se presentan en paquetes rosa empolvado dirigidos a las mujeres de la UNMC. Su olor es tan intenso que a veces se utilizan para ahuyentar insectos de las tiendas de campaña. Pese al esfuerzo, casi nadie los elige y suelen permanecer intactos en las expendedoras, desafiando en silencio a que alguien los pruebe. Que realmente gusten a alguien es otra cuestión.
rmc-lore-examinable-kierland-electro-golds = Popularizados por trabajadores de Novaris durante la construcción de su estación principal, estos cigarrillos se encendían con facilidad, ardían de manera uniforme y ofrecían una experiencia sencilla y fiable. Su sabor seco y terroso y su combustión estable los convirtieron rápidamente en un producto básico colonial. Kierlan amplió más tarde la producción en mundos agrícolas fronterizos y cerró acuerdos comerciales exclusivos con la UNMC.
rmc-lore-examinable-emerald-greens = Reconocibles al instante por costar menos incluso que el agua, estos cigarrillos se han vuelto omnipresentes allí donde escasean el presupuesto y la moral. Nadie sabe con certeza qué contiene la mezcla, pero casi todos coinciden en que nadie compra Emerald Greens por su sabor.

rmc-lore-examinable-boots-07 = Gran parte de la revista describe la armadura defensiva B18, diseñada para volver invencible al Marine moderno. Acaba de superar las pruebas, lo que ha elevado las expectativas de los altos mandos sobre esta nueva pieza de equipo.
rmc-lore-examinable-boots-45 = La primera parte del artículo explica el mantenimiento básico de armas secundarias e incluye un pequeño anuncio de un armero muy conocido de la estación Gateway. La segunda describe las mejores posturas para dormir con el arma bajo la almohada por si se produce alguna actividad sediciosa inesperada.
rmc-lore-examinable-boots-58 = El artículo describe las experiencias de los veteranos del 1.er Batallón FORECON durante la campaña de Tientsin y el hostil entorno selvático que tuvieron que atravesar al combatir contra la SPP y las guerrillas locales.
rmc-lore-examinable-boots-113 = El artículo relata los feroces combates urbanos que los Marines libraron contra colonos humanos en Marte durante los primeros tiempos de su colonización. Mientras Weyland-Yutani se expandía por la frontera roja, encontró resistencia armada de colonos contrarios a la expansión corporativa. Las PMC de Weyland-Yutani, con ayuda de fuerzas cercanas de la UNMC, derrotaron a los insurgentes. El artículo recoge testimonios de tripulantes de carros sobre la eficacia de sus nuevos carros de combate principales y avistamientos recientes de operadores MARSOC en la zona de operaciones. El conflicto supuso uno de los primeros usos documentados de bombardeo orbital de la UNMC en combate activo, con participación de la UNS Omaha.
rmc-lore-examinable-boots-150 = Gran parte de este número explica que las raciones de campaña de la SPP no están normalizadas y se producen localmente. Por ello, entre las raciones capturadas o confiscadas se han encontrado elecciones tan peculiares como hígado de pato, huevos centenarios, lutefisk, morro de cerdo en vinagre, callos enlatados y aperitivos de rábano confitado deshidratado.

rmc-lore-examinable-orrery-65 = La mitad de este número está dedicada al rumor de que un alto ejecutivo presentó por error su informe trimestral de beneficios de Danton's Perch ante la División de Despacho de las PMC. Después aparece un debate entre dos ejecutivos de Servicios Especiales sobre la creación de una colonia en el sistema Mu Arae. Uno propone un recolector suborbital de gases en torno a un gigante gaseoso; el otro prefiere la verde luna del planeta. A mitad del debate ambos pierden la compostura y empiezan a insultarse. El resto del artículo está fuertemente censurado.
rmc-lore-examinable-orrery-175 = El artículo central presenta una nueva nave para la Armada, diseñada tanto para soportar toda clase de daños y ataques como para llevar potencia de fuego suficiente para destruir una ciudad. Es un proyecto conjunto de la TSE y Weyland-Yutani e incluye entrevistas con los ingenieros imperiales y de WeYa que trabajan en la nave. Aunque no revela información confidencial, las numerosas menciones a cañones de riel, láseres triples de defensa puntual y baterías de tubos lanzamisiles dan una buena idea de su poder.
rmc-lore-examinable-orrery-184 = Este número especial cubre varios proyectos de Weyland-Yutani autorizados para su publicación por los accionistas y el director de división. Destacan la unidad mezcladora UY-21, que corrige la tendencia de la UY-20 a explotar con el calor; un «prototipo portátil de láser pesado de minería» capaz de cortar roca como mantequilla; y el sistema antiaéreo portátil TYPHOON EK-403, destinado a las PMC. A mitad del número se ofrece un cupón de «dos por uno» para un paquete de cerveza Sequoia que, al parecer, caducó al día siguiente de publicarse.
rmc-lore-examinable-orrery-34 = Gran parte de este número está dedicada a la amplia variedad de prendas que están de moda entre los ejecutivos de Weyland-Yutani de cada región de la galaxia. Las elecciones del borde interior resultan algo llamativas, pero elegantes y atractivas. Trajes estilizados con precios de cuatro cifras y corbatas impecables dominan la sección. Más cerca de la frontera aparecen opciones diferentes, desde chaquetas gruesas capaces de resistir frentes fríos hasta pantalones cortos de moda que mantienen frescos a los ejecutivos que trabajan bajo un calor sofocante. El artículo también menciona los esfuerzos de I+D por redefinir y mejorar las clásicas «We-Yu Stompers».

rmc-lore-examinable-orrery-202 = El tema principal es el programa de sintéticos de Weyland-Yutani y el enorme éxito del despliegue de la tercera generación. Compara los defectos de la generación 2, como su construcción relativamente frágil y su tendencia a sufrir averías, con los avances de la generación 3, que pretende corregir estos problemas y elevar el estándar para futuros proyectos. También explica que el lanzamiento aumentó un 4 % la cotización de WEYA y que numerosas naciones y organizaciones han invertido en sintéticos de tercera generación, entre ellas la TSE, la UN y organismos policiales como la CMP y TSEPA.
rmc-lore-examinable-orrery-217 = Este número se centra en los activos de la compañía militar privada Silverguard de Weyland-Yutani, como AZURE-15. Desplegados para asegurar, proteger o adquirir activos corporativos, estos mercenarios trabajan exclusivamente para Weyland-Yutani y reciben entrenamiento y equipo comparables a los de muchos ejércitos regulares. Se mencionan armas como la SSG-45 y la M80, además de armaduras de última generación. El artículo analiza el éxito de las PMC al desarticular células agitadoras de la CLF y proteger los activos de WEYA. Más adelante, una nota menor trata la posible degradación de un supervisor ejecutivo de Servicios Especiales que no informó a sus superiores de un accidente industrial de gran escala bajo su responsabilidad.
rmc-lore-examinable-orrery-220 = Este número aborda los problemas recientes de la División de Logística de Weyland-Yutani, especialmente en la frontera de Zypheron. Las tensiones entre la UN/TSE y la SPP y los disturbios provocados por la CLF han afectado a la cadena de suministro corporativa, aumentando el coste de los bienes de consumo y reduciendo el número de puertos aptos para reabastecimiento y repostaje. También presenta planes para reducir costes, como construir depósitos adicionales en lugares clave —entre ellos OCP-583— y estrechar los vínculos comerciales con organizaciones accionistas como la UN y la TSE. Por último, analiza nuevos cargueros capaces de transportar cincuenta mil contenedores por toda la galaxia.
rmc-lore-examinable-orrery-258 = Este número relata los esfuerzos por fundar una colonia en LV-676, un mundo templado del borde medio. Aunque se identificó pronto como posible emplazamiento, la colonización no se planteó seriamente hasta tiempos recientes. Tras una reunión de accionistas en 2102, Servicios Especiales de Weyland-Yutani recibió autorización para comenzar. Los 234 integrantes iniciales y dos sintéticos reclamaron el planeta y lo llamaron «Fort Denst». El terreno difícil, los purificadores de agua averiados y los fuertes vientos causaron víctimas y heridos, pero la población resistió. Hoy la colonia alberga a 1430 personas y es famosa por exportar queso.

rmc-lore-examinable-weya-windbreaker = Resultado de un programa de I+D de siete años, este cortavientos incorpora regulación avanzada de temperatura, un diseño cómodo y un exterior hidrófobo, por lo que resulta perfecto para casi cualquier clima. Por desgracia, nadie pensó en añadirle una capucha.
rmc-lore-examinable-atmospheric-composition-scanner = Un robusto dispositivo portátil capaz de recopilar datos atmosféricos locales mediante tecnología avanzada que I+D de WEYA se empeña en mantener en secreto. Se utiliza en toda la galaxia para buscar fugas de gas, comprobar el avance de la terraformación y reunir datos científicos sobre entornos exoplanetarios. WEYA, la TSE y la UN lo usan desde 2078 casi sin modificaciones, y es famoso por su fiabilidad, especialmente en condiciones extremas.

rmc-lore-examinable-spp-survival-ration = Producidas en masa como alimento de emergencia, estas raciones abundan por todos los Pueblos Progresistas y están repletas de suplementos nutricionales. Muchos ciudadanos las consumen por comodidad en lugar de barritas más sabrosas o como complemento de otros platos. Pese a los mitos populares de la UN, no son la ración de campaña estándar de la Infantería Naval de la SPP, pero se emplean cuando se agotan las auténticas raciones militares, como cabe esperar de un alimento de supervivencia.

rmc-lore-examinable-m13-extended-recoil-compensator = Un dispositivo de boca de producción limitada desarrollado por AEGIS Armaments. El compensador canaliza los gases para contrarrestar el retroceso y aumentar ligeramente la velocidad del proyectil mediante presión concentrada, mejorando de forma marginal el rendimiento balístico.

rmc-lore-examinable-bug-juice = La bebida proteínica «Bug Juice», conocida habitualmente como Bug Juice, es una bebida barata y calórica fabricada con insectos criados y procesados, como cucarachas, gusanos de la harina y escarabajos. Distintos fabricantes la venden en cartones y botellas y se consume mucho en la Frontera. Se considera a la vez bebida y alimento y aporta proteínas y agua.

rmc-lore-examinable-soylent = MRD fue diseñada en 2173 como sustituto alimenticio para trabajadores sometidos a esfuerzos intensos. Se retiró varias veces del mercado tras notificarse trastornos gastrointestinales como náuseas, vómitos y diarrea. Se desarrolló una fórmula mejorada, pero la marca ya estaba desprestigiada, así que la bebida quedó como reserva alimentaria de emergencia para uso interno de la Compañía.

rmc-lore-examinable-t70-bag-phone = Un voluminoso bolso que contiene un teléfono, una antena y una batería de gran autonomía, además de espacio para otros objetos. Estos teléfonos civiles emplean tecnología similar a la de una mochila radiotelefónica, pero en un formato más compacto, aunque menos resistente. Siguiendo de cerca las nuevas líneas de teléfonos de bolso de Novaris Industries, el T70 está dirigido a clientes de mayor poder adquisitivo, sobre todo del sector empresarial, y tiene un precio considerable.
    El modelo incorpora varias mejoras respecto a sus predecesores: pesa menos, tiene un diseño más ergonómico y ofrece una recepción superior.

rmc-lore-examinable-bag-phone = Un radioteléfono básico sujeto a un bolso. La solapa tiene una pequeña abertura para el transceptor. Es un diseño bastante antiguo: uno de los primeros teléfonos civiles de bolso patentados por Novaris Industries.
    Cuando venció la patente, numerosas corporaciones adoptaron el diseño y lo vendieron ampliamente. Hoy, pese a su gran tamaño y peso, el modelo sigue siendo habitual entre consumidores ahorradores por su coste relativamente bajo y su fiabilidad frente a alternativas más modernas.
