[adminlogs]
server_name = "alamo"

[game]
desc = "Únete y juega como marine, respondiendo a una misteriosa señal de socorro, o como xenónido, expandiendo tu colmena y defendiéndola de los marines."
hostname = "[ES][RP MEDIO] Cuerpo de Marines de Rouny: Alamo [Este de EE. UU.]"

[hub]
tags = "lang:es,region:am_n_e,rp:med"

[loki]
name = "alamo"
