[adminlogs]
server_name = "normandy"

[game]
desc = "Modo de juego PvE especial oficial de RMC, dirigido por un director de juego."
hostname = "[ES][RP ALTO] PvE Cuerpo de Marines de Rouny: Normandy [Este de EE. UU.]"

[hub]
tags = "lang:es,region:am_n_e,rp:high"

[loki]
name = "normandy"
