using System.Linq;
using Content.Client._CMU14.Localizations;
using Content.Shared.AU14.Ambassador;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.AU14.Ambassador;

[GenerateTypedNameReferences]
public sealed partial class AmbassadorThirdPartyWindow : DefaultWindow
{
    public event Action<string>? OnCallThirdParty;

    private List<string> _thirdPartyIds = new();
    private Dictionary<string, (string DisplayName, float Cost)> _thirdParties = new();
    private HashSet<string> _calledParties = new();
    private string? _selectedThirdPartyId;

    public AmbassadorThirdPartyWindow()
    {
        RobustXamlLoader.Load(this);

        ThirdPartyList.OnItemSelected += args =>
        {
            if (args.ItemList[args.ItemIndex].Metadata is string id)
                SelectThirdParty(id);
        };

        ThirdPartyList.OnItemDeselected += args =>
        {
            if (args.ItemList[args.ItemIndex].Metadata is string id && id == _selectedThirdPartyId)
                SelectThirdParty(null);
        };

        CallBtn.OnPressed += _ =>
        {
            if (_selectedThirdPartyId is { } id &&
                _thirdParties.ContainsKey(id) &&
                !_calledParties.Contains(id))
            {
                OnCallThirdParty?.Invoke(id);
                StatusLabel.Text = Target(
                    "cmu-ambassador-third-party-requesting",
                    "Requesting support...");
            }
        };
    }

    public void UpdateState(AmbassadorThirdPartyBuiState s)
    {
        BudgetLabel.Text = Target(
            "cmu-ambassador-ui-budget",
            $"Budget: ${s.Budget:F0}",
            ("budget", s.Budget.ToString("F0")));

        var newIds = s.CallableParties.Keys.ToList();
        var changed = !_thirdPartyIds.SequenceEqual(newIds) || !_calledParties.SetEquals(s.CalledParties);

        _thirdParties = s.CallableParties;
        _calledParties = s.CalledParties;

        if (changed)
        {
            var previousSelectedKey = _selectedThirdPartyId;

            _thirdPartyIds = newIds;
            ThirdPartyList.Clear();

            if (_thirdPartyIds.Count == 0)
            {
                StatusLabel.Text = Target(
                    "cmu-ambassador-third-party-no-available",
                    "No third parties available to call.");
                SelectThirdParty(null);
                CostLabel.Text = Target("cmu-ambassador-third-party-cost-na", "Cost: N/A");
                return;
            }

            StatusLabel.Text = "";

            for (int i = 0; i < _thirdPartyIds.Count; i++)
            {
                var id = _thirdPartyIds[i];
                var info = s.CallableParties[id];
                var label = _calledParties.Contains(id)
                    ? Target(
                        "cmu-ambassador-third-party-list-entry-called",
                        $"{info.DisplayName} - ${info.Cost:F0} [CALLED]",
                        ("name", info.DisplayName),
                        ("cost", info.Cost.ToString("F0")))
                    : Target(
                        "cmu-ambassador-third-party-list-entry",
                        $"{info.DisplayName} - ${info.Cost:F0}",
                        ("name", info.DisplayName),
                        ("cost", info.Cost.ToString("F0")));

                ThirdPartyList.Add(new ItemList.Item(ThirdPartyList)
                {
                    Text = label,
                    Metadata = id,
                });
            }

            var restoreIdx = previousSelectedKey != null ? _thirdPartyIds.IndexOf(previousSelectedKey) : -1;
            var selectIdx = restoreIdx >= 0 ? restoreIdx : _thirdPartyIds.FindIndex(id => !_calledParties.Contains(id));
            if (selectIdx < 0)
                selectIdx = 0;

            ThirdPartyList[selectIdx].Selected = true;
            SelectThirdParty(_thirdPartyIds[selectIdx]);
        }
        else
        {
            SelectThirdParty(_selectedThirdPartyId);
        }
    }

    private void SelectThirdParty(string? id)
    {
        _selectedThirdPartyId = id;

        if (id == null || !_thirdParties.TryGetValue(id, out var info))
        {
            CostLabel.Text = _thirdPartyIds.Count == 0
                ? Target("cmu-ambassador-third-party-cost-na", "Cost: N/A")
                : Target("cmu-ambassador-third-party-cost-zero", "Cost: $0");
            CallBtn.Disabled = true;
            return;
        }

        CostLabel.Text = Target(
            "cmu-ambassador-third-party-cost",
            $"Cost: ${info.Cost:F0}",
            ("cost", info.Cost.ToString("F0")));
        CallBtn.Disabled = _calledParties.Contains(id);
    }

    private static string Target(
        string key,
        string fallback,
        params (string, object)[] arguments)
    {
        return CMULocExtension.GetString(key, fallback, arguments);
    }
}
