using Content.Client._CMU14.Localizations;
using Content.Shared.AU14.Ambassador;
using Content.Shared.AU14.ColonyEconomy;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.AU14.Ambassador;

[GenerateTypedNameReferences]
public sealed partial class AmbassadorConsoleWindow : DefaultWindow
{
    public AmbassadorConsoleWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateState(AmbassadorConsoleBuiState s)
    {
        BudgetLabel.Text = Target(
            "cmu-ambassador-ui-budget",
            $"Budget: ${s.Budget:F0}",
            ("budget", s.Budget.ToString("F0")));
        FactionLabel.Text = Target(
            "cmu-ambassador-ui-faction",
            $"Faction: {s.FactionName}",
            ("faction", s.FactionName));

        // Economy with prices
        EmbargoStatus.Text = s.EmbargoActive
            ? Target(
                "cmu-ambassador-ui-embargo-active",
                $"[ACTIVE] Embargo: -20% submission payouts (${s.EmbargoCostPerMinute:F0}/min)",
                ("cost", s.EmbargoCostPerMinute.ToString("F0")))
            : Target(
                "cmu-ambassador-ui-embargo-inactive",
                $"Embargo: Inactive (${s.EmbargoCostPerMinute:F0}/min)",
                ("cost", s.EmbargoCostPerMinute.ToString("F0")));
        TradePactStatus.Text = s.TradePactActive
            ? Target(
                "cmu-ambassador-ui-trade-pact-active",
                $"[ACTIVE] Trade Pact: +20% submission payouts (${s.TradePactCostPerMinute:F0}/min)",
                ("cost", s.TradePactCostPerMinute.ToString("F0")))
            : Target(
                "cmu-ambassador-ui-trade-pact-inactive",
                $"Trade Pact: Inactive (${s.TradePactCostPerMinute:F0}/min)",
                ("cost", s.TradePactCostPerMinute.ToString("F0")));

        // Comms jam with price
        CommsJamStatus.Text = s.CommsJamActive
            ? Target(
                "cmu-ambassador-ui-comms-jam-active",
                $"[ACTIVE] Comms Jammed - All radio blocked (${s.CommsJamCostPerMinute:F0}/min)",
                ("cost", s.CommsJamCostPerMinute.ToString("F0")))
            : Target(
                "cmu-ambassador-ui-comms-normal",
                $"Comms: Normal (${s.CommsJamCostPerMinute:F0}/min)",
                ("cost", s.CommsJamCostPerMinute.ToString("F0")));

        // Broadcast cost
        BroadcastCostLabel.Text = Target(
            "cmu-ambassador-ui-broadcast-cost",
            $"Broadcast cost: ${s.BroadcastCost:F0} per message",
            ("cost", s.BroadcastCost.ToString("F0")));

        // Signal with prices
        var signalText = Target("cmu-ambassador-ui-signal-normal", "Signal: Normal");
        if (s.SignalBoostActive)
        {
            signalText = Target(
                "cmu-ambassador-ui-signal-boost-active",
                $"[ACTIVE] Signal Boost - Third parties arrive faster (${s.SignalBoostCostPerMinute:F0}/min)",
                ("cost", s.SignalBoostCostPerMinute.ToString("F0")));
        }
        else if (s.SignalJamActive)
        {
            signalText = Target(
                "cmu-ambassador-ui-signal-jam-active",
                $"[ACTIVE] Signal Jam - Third parties arrive slower (${s.SignalJamCostPerMinute:F0}/min)",
                ("cost", s.SignalJamCostPerMinute.ToString("F0")));
        }
        else
        {
            signalText = Target(
                "cmu-ambassador-ui-signal-normal-costs",
                $"Signal: Normal (Boost: ${s.SignalBoostCostPerMinute:F0}/min | Jam: ${s.SignalJamCostPerMinute:F0}/min)",
                ("boost", s.SignalBoostCostPerMinute.ToString("F0")),
                ("jam", s.SignalJamCostPerMinute.ToString("F0")));
        }
        SignalStatus.Text = signalText;

        // Radar scan button with price
        ScanRadarBtn.Text = Target(
            "cmu-ambassador-ui-scan-radar-cost",
            $"Scan Radar (${s.RadarScanCost:F0})",
            ("cost", s.RadarScanCost.ToString("F0")));

        // Economy status
        UpdateEconomyStatus(s.EconomyStatus);

        // Update radar list
        RadarList.RemoveAllChildren();
        if (s.RadarList.Count == 0)
        {
            RadarList.AddChild(new Label
            {
                Text = Target(
                    "cmu-ambassador-ui-no-scan-data",
                    "No scan data. Press 'Scan Radar' to detect incoming shuttles."),
            });
        }
        else
        {
            foreach (var name in s.RadarList)
            {
                RadarList.AddChild(new Label { Text = $"• {name}" });
            }
        }
    }

    private void UpdateEconomyStatus(EconomyStatusState econ)
    {
        EconomyStatusPanel.RemoveAllChildren();
        EconomyStatusPanel.AddChild(new Label
        {
            Text = Target(
                "cmu-ambassador-ui-sales-tax",
                $"Sales Tax: {econ.SalesTaxPercent:F0}%",
                ("percent", econ.SalesTaxPercent.ToString("F0"))),
        });
        EconomyStatusPanel.AddChild(new Label
        {
            Text = Target(
                "cmu-ambassador-ui-income-tax",
                $"Income Tax: {econ.IncomeTaxPercent:F0}%",
                ("percent", econ.IncomeTaxPercent.ToString("F0"))),
        });
        EconomyStatusPanel.AddChild(new Label
        {
            Text = Target(
                "cmu-ambassador-ui-transit-tariff",
                $"Transit Tariff: {econ.TransitTariffPercent:F0}%",
                ("percent", econ.TransitTariffPercent.ToString("F0"))),
        });

        if (econ.ActiveEmbargoes.Count > 0)
            EconomyStatusPanel.AddChild(new Label
            {
                Text = Target(
                    "cmu-ambassador-ui-active-embargoes",
                    $"Active Embargoes: {string.Join(", ", econ.ActiveEmbargoes)}",
                    ("factions", string.Join(", ", econ.ActiveEmbargoes))),
                StyleClasses = { "Caution" },
            });
        else
            EconomyStatusPanel.AddChild(new Label
            {
                Text = Target("cmu-ambassador-ui-no-embargoes", "Embargoes: None"),
                StyleClasses = { "LabelSubText" },
            });

        if (econ.ActiveTradePacts.Count > 0)
            EconomyStatusPanel.AddChild(new Label
            {
                Text = Target(
                    "cmu-ambassador-ui-active-trade-pacts",
                    $"Active Trade Pacts: {string.Join(", ", econ.ActiveTradePacts)}",
                    ("factions", string.Join(", ", econ.ActiveTradePacts))),
            });
        else
            EconomyStatusPanel.AddChild(new Label
            {
                Text = Target("cmu-ambassador-ui-no-trade-pacts", "Trade Pacts: None"),
                StyleClasses = { "LabelSubText" },
            });
    }

    private static string Target(
        string key,
        string fallback,
        params (string, object)[] arguments)
    {
        return CMULocExtension.GetString(key, fallback, arguments);
    }
}
